### PR TITLE
Adjust cl imports

### PR DESCRIPTION
**Pull request by ThomasHepworth**
As discussed, here's a slightly cleaner layout for our comparisons so that we obscure some of the imports/exports to the users.

**Some background:**
At present, when you use:
```python
import duckdb.duckdb_comparison_level_library as cll
```
all of our base classes are imported, alongside the classes we wish end users to take advantage of.

This means it’s possible for people to use:
```python
cll.ElseLevelBase
```
by accident, should they not read the docs or know what they’re doing.

This used to be more of an issue than it is now, where the _level functions were imported and used in duckdb_comparison_library.py and would cause issues if you weren’t paying attention.

### CODE REVIEW

**Comment by ThomasHepworth** [comment]
Another potential layout - if you'd prefer `_comparison_imports.py` was cleaned up:
```
.
{linker}_linker.py
├── {linker}_helpers
│   └── comparison_level_library.py
│   └── comparison_template_library.py
│   └── comparison_library.py
```

**Comment by RossKen** [comment]
I think I prefer the current structure rather than your alternative ☝️

**Review by RossKen — CHANGES_REQUESTED** [review]
I really like this change, and all seems to work as expected.

Just one thing to change - can you update the [comparison and comparison level dev guides](https://moj-analytical-services.github.io/splink/dev_guides/comparisons/new_library_comparisons_and_levels.html) to reflect the changes of the folder structure? There are only a couple of references, then I am happy to approve.

**Review by RossKen — APPROVED** [review]

**Review by RossKen — CHANGES_REQUESTED** [review]
Sorry didn't mean to approve - there are tests now failing

**Review by RossKen — APPROVED** [review]

**Pull request merged**
