### PR TITLE
(WIP) 961 ideas for improving caching

### PR DESCRIPTION
**Pull request by RobinL**
Major changes here will be:
- All physically materialised tables will be given a `physical_name` name with a hash
-No functions will implicitly rely on a cache of tables called `df_concat` and `df_concat_with_tf` already having been created
- The `SplinkDataFrame` of (`templated_name`) `df_concat` and `df_concat_with_tf` will have to be passed into any pipelines that rely on those tables existing.
- Where these tables are needed, they will be explicitly created (and loaded from cache if necessary)
- Renamed these tables to make it more explicit what they are
- Introduced a UUID which is unique to each linker which is included in cached table names.  To invalidate the entire cache, you just need to change this UUID.  This in turn will change physical names (the hash part of the name), and hence these tables will not be found in the cache

### CODE REVIEW

**Comment by RobinL** [comment]
Started along the following lines, where we prefix tables with `__splink__{uid}`, but it means we have to be careful about passing {uid} everywhere which makes the code harder to follow.

I'm going to revert it, and instead try an approach of injecting a comment into the top of every SQL pipeline with the UID, which should have the same effect.

https://github.com/moj-analytical-services/splink/compare/575fce0d6538435ce571701ca6c3860fc95b1dfb...b6ab937780d37b894ce04d122aab9c9df0efbe06

**Comment by RobinL** [comment]
remember to remove `materialise_as_hash` from `execute_sql`

**Comment by mamonu** [comment]
> Started along the following lines, where we prefix tables with `__splink__{uid}`, but it means we have to be careful about passing {uid} everywhere which makes the code harder to follow.
> 
> I'm going to revert it, and instead try an approach of injecting a comment into the top of every SQL pipeline with the UID, which should have the same effect.

Just a note : 

Since now splink doesnt only the spark backend only this might not be as helpful but there is a UUID generator which is spark sql native. Depending If this is run on each row somewhere it should be faster than the python version.
Could be useful? Perhaps Would this improve performance? only the perf tests will show 😃 

```python
import pyspark.sql.functions as f
df.withColumn("uuid", f.expr("uuid()")).show(truncate=False)

```

**Comment by RobinL** [comment]
We've had various reports (e.g. from databricks) of issues due to the way that Splink caches intermediate tables.  These don't crop up very often, but often enough to be annoying.

The two contexts in which it's an issue are:
(1)  People running Splink from live data where cache invalidation is required because the input data has changed
(2)  People running multiple Splink linkers in a single Spark session

As a reminder, we cache intermediate tables for performance reasons.  For example, when running iterative algorithms, some tables need to be computed once and used many times.  Without caching, they'd have to be repeatedly recalculated.

The problem is that in the past, I've been computing a couple of tables and saving them to the database, most notably `__splink__df_concat_with_tf`.  For many operations, Splink then checks to see whether that table exists before recomputing.

The problem is that to solve 1) and 2) above, the cache should be linker-specific, and capable of being invalidated if the data changes.  At the moment, ANY linker will find `__splink__df_concat_with_tf` and re-use it.  So if there are two linkers in play, you have a problem.

The PR I'm working on solves this by assigning a UID to each linker.  The linker then checks for a specific table `__splink__df_concat_with_tf_{hash_from_uid}`.

This solves these two issues:
1.  One linker no longer finds another linker's cache
2. Cache invalidation is as simple as changing a linker's UID

**Comment by RobinL** [comment]
Todo:

- [ ] Ensure all diagnostics work
- [ ] Ensure register table methods work correctly
- [ ] Ensure real time linking functions work

**Comment by RobinL** [comment]
How should `_table_exists_in_database` and `register_table` work?

Options:

**Option 1**.   Cache is stored in memory as dict

Splink maintains an in-memory mapping of templated names vs physical names.  When a table is registered, the templated names part of this mapping is checked to see whether it has a value.

The main problem with this approach is that it's at least possible that the in-memory mapping and the database get out of sync

**Option 2**.   When you register a table or want to check if a table exists, you have to first generate the table's sql and hash it to know what name it should have.  

This is problematic because the sql queue is stateful and you can only have one.  So if you've already added some SQL to the queue but not executed it, there's no easy way of checking whether a table exists.  Because you'd need a new queue, youd need to generate some sql and then find the hashed table name.

**Option 3**. For table_exists_in_database, fuzzy search for the table WITHOUT the hash.  

This  is no good because the hash is the thing that allows us to do proper cache invalidation and avoids conflicts between multiple linkers

**Comment by RobinL** [comment]
Tom and I chatted.  Here are some notes:

- Tom suggested that the hash for any table can be derived from hashing the settings object, rather than hashing the SQL.  This makes it much easier to 'look up' the hash that should be associated with a particular table.  You don't need to attempt to generate the SQL - just use the settings object
-

**Pull request closed without merging**
