### PR TITLE
change required for duckdb v0.4.1 release

### PR DESCRIPTION
**Pull request by chloepugh**
Addresses issue #737.

This PR is only ready to merge once duckdb v0.4.1 is released.

### CODE REVIEW

**Comment by ThomasHepworth** [comment]
Thanks Chloe 👍 

Don't worry about the tests failing.

**Comment by RobinL** [comment]
0.5.0 planned release for 2022-09-05 so prob best to merge these fixes after release https://twitter.com/duckdb/status/1564140382895886336

**Comment by RobinL** [comment]
I wonder whether we want to make this robust to people on older versions of duckdb like:
```
    def _table_exists_in_database(self, table_name):
        sql = f"PRAGMA table_info('{table_name}');"

        # From duckdb 0.5.0, duckdb will raise a CatalogException
        # which does not exist in 0.4.0 or before

        try:
            from duckdb import CatalogException

            error = CatalogException
        except ImportError:
            error = RuntimeError

        try:
            self._con.execute(sql)
        except error:
            return False
        return True
```

**Comment by RobinL** [comment]
Closing in favour of https://github.com/moj-analytical-services/splink/pull/750 (so I could commit on top of the fork)

**Pull request closed without merging**
