### PR TITLE
add charts plugin

### PR DESCRIPTION
**Pull request by RossKen**
### Type of PR

- [X] BUG
- [ ] FEAT
- [ ] MAINT
- [ ] DOC

### Give a brief description for the solution you have provided

Chart rendering has been a pain in the docs for a while. This charts plugin for mkdocs appears to fix these issues and charts render with more reliability than they do currently.

### PR Checklist

- [ ] Added documentation for changes
- [ ] Added feature to example notebooks or tutorial (if appropriate)
- [ ] Added tests (if appropriate)
- [ ] Made changes based off the latest version of Splink
- [ ] Run the [linter](https://moj-analytical-services.github.io/splink/dev_guides/changing_splink/lint.html)

### CODE REVIEW

**Comment by RobinL** [comment]
Nice.  This also probably opens the door to have something like a chart gallery in the docs somewhere that has an example of each chart and an explanation, something I've been meaning to do for a while

**Comment by RossKen** [comment]
> Nice. This also possibly/probably opens the door to have something like a chart gallery in the docs somewhere that has an example of each chart and an explanation, something I've been meaning to do for a while

Yea, that sounds like a really good idea. I feel like I refer people to the visualisation section of the tutorial so having a central place for all charts would be fantastic. Plus it is a great way to show off all of our interactive things so people can have a play.

**Review by ADBond — APPROVED** [review]
Very cool, looks like a useful addition 👍

**Comment by RossKen** [comment]
NB #1503 opened to explore creating a charts gallery

**Pull request merged**
