### PR TITLE
Migrate tests for Splink 4 (`ComparisonLevelCreator` and `ComparisonCreator` and related changes)

### PR DESCRIPTION
**Pull request by ADBond**
This is a branch to translate our existing (Splink 3) tests to work on the new `ComparisonLevelCreator` class (see #1689, #1703). This will be updated as and when new features get implemented in Splink 4, specifically the various missing comparison levels, and the library and template comparisons)

The changes to `splink/` itself should all be relatively minimal, and mostly pertain to allowing the tests to run - anything sufficiently substantial will instead get its own PR to `splink4_dev`. That said, it is probably good to check the changes there particularly carefully in case I accidentally do anything silly.

The rest of the PR is large, but most of the changes should be fairly straightforward - mostly renaming + the small changes needed with updated syntax. I will try and highlight anything particularly noteworthy so that it doesn't get lost in the noise.

Progress:

| Feature | Implemented | Added to this branch |
| ---- | ---- | ---- |
| Core levels (exact, null, else) | #1689  | ✅  |
| `LevenshteinLevel` | #1689  |  ✅  |
| `DatediffLevel` | #1705 (+#1837) | ✅  |
| `JaroWinklerLevel` | #1717  | ✅  |
| `ColumnsReversedLevel` | #1726  | ✅  |
| `JaroLevel` | #1728  | ✅  |
| `JaccardLevel` | #1728  | ✅  |
| `DamerauLevenshteinLevel` | #1728  | ✅  |
| `DistanceInKMLevel` | #1727  | ✅  |
| `ArrayIntersectLevel` | #1753 | ✅  |
| `PercentageDifferenceLevel` | #1758 | ✅  |
| `CustomLevel` | #1768 | ✅ |
| `DistanceFunctionLevel` | #1860 | ✅ |
|  |
| `or_` | #1777 | ✅ (#1783) |
| `and_` | #1777 | ✅ (#1783) |
| `not_` | #1777 | ✅ (#1783) |
|  |
| `ExactMatch` | #1721  | ✅  |
| `LevenshteinAtThresholds` | #1721  | ✅  |
| `CustomComparison` | #1768 | ✅ |
| `DamerauLevenshteinAtThresholds` | #1770 | ✅ |
| `JaccardAtThresholds` | #1770 | ✅ |
| `JaroAtThresholds` | #1770 | ✅ |
| `JaroWinklerAtThresholds` | #1770 | ✅ |
| `DistanceInKMAtThresholds` | #1815 | ✅ (#1816) |
| `DatediffAtThresholds` | #1782 | ✅ |
| `ArrayIntersectAtSizes` | #1770 | ✅ |
| `DistanceFunctionAtThresholds` | #1860 | ✅ |
|  |
| `EmailComparison` | #1840  | ✅ |
| `DateComparison` | #1856 | ✅ (#1857) |
| `NameComparison` | #1856  | ✅ (#1857)  |
| `PostcodeComparison` | #1856  | ✅ (#1857)  |
| `ForenameSurnameComparison` | #1856  | ✅ (#1857)  |
|  |
| `InputExpression` (for `regex_extract`, `lower`, etc) | #1782 | ✅  |
| comparison tf adjustments | #1812 | ✅ (#1813) |
| `NullLevel` regex validation | #1819 (+#1834) | ✅ |
| Paremeter validation (e.g. -ve array sizes) | #1861 | ✅ |

Tests now actually _run_ [although some have been temporarily disabled], so we can start to get semi-useful feedback.

Number of failing tests [postgres, sqlite respectively in parentheses where included]:

~~110~~
~~96~~
~~93~~
~~85~~
~~64~~
~~55~~
~~52~~
~~57 😭~~
~~56~~
~~48~~
~~46~~
~~44~~
~~40~~
~~39~~
~~35~~
~~33 (5, 3)~~
~~33 (15, 12)~~
~~33 (5, 2)~~
~~31~~
~~32 😭~~
~~25 (5, 0)~~
~~24 (3, 0)~~
~~8 (4, 2)~~
~~8 (4, 0)~~
0 (0, 0) 🥳 🎉 🎊  ✅ 😎

### CODE REVIEW

**Comment by RobinL** [comment]
@ADBond  to add datediff and the other levels I've done, shall i just do a PR pointing at this branch?

**Comment by ADBond** [comment]
> @ADBond to add datediff and the other levels I've done, shall i just do a PR pointing at this branch?

It's okay, I have merged in `splink4_dev` + started changing all the relevant test modules

**Comment by RobinL** [comment]
thanks!

**Review by RobinL — APPROVED** [review]
Incredible work!

image

**Pull request merged**
