### PR TITLE
Expectation maximisation speedup option

### PR DESCRIPTION
**Pull request by aymonwuolanne**
### Type of PR

FEAT

### Is your Pull Request linked to an existing Issue or Pull Request?
Relates to #1363 

### PR Checklist

- [ ] Added documentation for changes
- [ ] Added feature to example notebooks at tutorials in [splink_demos](https://github.com/moj-analytical-services/splink_demos) (if appropriate)
- [x] Added tests (if appropriate)
- [x] Made changes based off the latest version of Splink
- [x] Run the [linter](https://moj-analytical-services.github.io/splink/dev_guides/changing_splink/lint.html)

### CODE REVIEW

**Comment by RobinL** [comment]
This is great - thanks!  The core logic all looks good to me.

There's a minor adjustment i'd like to make around the settings object, just  for consistency with the rest of the codebase - are you happy for me to add commits on top?

**Comment by aymonwuolanne** [comment]
> This is great - thanks! The core logic all looks good to me.
> 
> There's a minor adjustment i'd like to make around the settings object, just for consistency with the rest of the codebase - are you happy for me to add commits on top?

Absolutely, feel free.

**Comment by RobinL** [comment]
I tried it out on our 1m row test dataset from Wikidata:

Blocking run 1:
New method: `Iteration time: 0.045393943786621094 seconds`
Old method: `Iteration time: 3.0039303302764893 seconds`
🎉 60x speedup

Blocking run 2, with a looser rule:
New method: `Iteration time: 0.12349581718444824 seconds`
Old method : `Iteration time: 104 seconds`
🎉 1000x speedup

**Review by RobinL — APPROVED** [review]
Excellent work thank you so much - didn't need any changes in the end when i thought about it a little more

**Comment by aymonwuolanne** [comment]
Great to see it's speeding it up that much!

**Pull request merged**
