### PR TITLE
James osmond pr chart threshold

### PR DESCRIPTION
**Pull request by RossKen**

### CODE REVIEW

**Comment by James-Osmond** [comment]
Looks like all tests have passed @RossKen - so in future I suppose forks should be merged to main only via another branch? Should there be a smoother way to do this (given you need certain access privileges to be able to make your own branch straight into the GH repo)?

**Comment by James-Osmond** [comment]
@ThomasHepworth , this makes sense to me - when I wrote this comment I didn't know I could run the tests through a PR on the fork itself, so happy with 1 in future. Much more straightforward for all of us I think.

**Comment by ThomasHepworth** [comment]
@James-Osmond do you know if Ross is content with these changes? I can review this PR if not.

**Comment by James-Osmond** [comment]
When he merged my other PR to this branch he was fine with the changes, think he was waiting for the tests to pass on this PR before completing the merge to master. They were taking a while and think he must have not had the chance to come back to them - but they've passed now!

**Comment by James-Osmond** [comment]
@ThomasHepworth When he merged my other PR to this branch he was fine with the changes, think he was waiting for the tests to pass on this PR before completing the merge to master. They were taking a while and think he must have not had the chance to come back to them - but they've passed now!

**Comment by RossKen** [comment]
Hey @ThomasHepworth @James-Osmond yes I am happy to merge!

**Review by ThomasHepworth — APPROVED** [review]

**Pull request merged**
