### PR TITLE
Additional columns and non-blocking (NEEDS ASSOCIATED TESTS)

### PR DESCRIPTION
**Pull request by samnlindsay**
This covers #79 and #80:

- Makes sure specified `additional_columns_to_retain` are consistently retained as `col_l` and `col_r`
- Updates `cartesian_block` to mirror `block_using_rules`
- If `blocking_rules` are empty in settings (still a required field) then `cartesian_block` is used to generate comparison table. 

Simple enough changes but want to have a conversation with Robin/Theo about how best to go about testing them.

### CODE REVIEW

**Comment by RobinL** [comment]
This looks good.

There's one thing that is non-obvious in the settings.  (Perhaps so non-obvious that your solution is better)

There's a setting called `cartesian_product` [here](https://github.com/moj-analytical-services/splink/blob/9b7712f40ca8a9b813024c3be605b3e37380f805/splink/files/settings_jsonschema.json#L251) that allows the user to explicitly state they want the Cartesian product.

The schema enforces the fact you can either have `blocking_rules` populated or `cartesian_product`, but not both, see [here](
https://github.com/moj-analytical-services/splink/blob/9b7712f40ca8a9b813024c3be605b3e37380f805/splink/files/settings_jsonschema.json#L7).  

Another option would therefore be to add a validation rule to the schema that says that `blocking_rules` must have 1 item or more - using the `minItems` key, see [here](https://stackoverflow.com/a/23301092/1779128)

**Comment by RobinL** [comment]
Note this is what you get if you add the `minItems` to the schema and try to validate:

```
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-2-dbef770ab8f2> in <module>
     28 
     29 }
---> 30 validate_settings(settings)

~/Documents/python_projects/fellegi_sunter_em_spark/splink/check_types.py in wrapper(*args, **kwargs)
     92 
     93 
---> 94         return func(*args, **kwargs)
     95 
     96     return wrapper

~/Documents/python_projects/fellegi_sunter_em_spark/splink/validate.py in validate_settings(settings_dict)
     87 
     88     if exception_raised:
---> 89         raise ValidationError(message)
     90 
     91 

ValidationError: There is an error in your settings dictionary. To quickly write a valid settings dictionary using autocompelte you might want to try our online tool https://robinlinacre.com/simple_sparklink_settings_editor/, or you can use the autocomplete features of VS Code - just copy and paste code from the following gist into VS Code, setting language mode to json, or having saved the file as a .json file
https://gist.github.com/RobinL/cfe1152dbd33ae26e05a43d9a0ec85b9

The details of the error are as follows:
[] is too short

Failed validating 'minItems' in schema['properties']['blocking_rules']:
    {'$id': '#/properties/blocking_rules',
     'description': 'Each rule is a SQL expression representing the '
                    'blocking rule, which will be used to create a join.  '
                    'The left table is aliased with `l` and the right '
                    'table is aliased with `r`. For example, if you want '
                    'to block on a `first_name` column, the blocking rule '
                    'would be `l.first_name = r.first_name`.  Note that '
                    'splink deduplicates the comparisons generated by the '
                    'blocking rules.',
     'examples': [['l.first_name = r.first_name AND l.surname = r.surname',
                   'l.dob = r.dob']],
     'items': {'$id': '#/properties/blocking_rules/items',
               'default': [],
               'examples': [['l.first_name = r.first_name AND l.surname = '
                             'r.surname',
                             'l.dob = r.dob']],
               'pattern': '^(.*)$',
               'title': 'Each item in the array is a SQL expression '
                        'represing a left join ON condition',
               'type': 'string'},
     'minItems': 1,
     'title': 'A list of one or more blocking rules to apply. Ignored if '
              'cartesian_product=true is set',
     'type': 'array'}

On instance['blocking_rules']:
    []
```

**Comment by RobinL** [comment]
Perhaps we could amend the `description` of blocking rules to include something like 'there must be at least one blocking rule.  If you want to take the cartesian product, set the `cartesian_product` key to `true` instead

**Comment by samnlindsay** [comment]
One way or another, improved documentation would obviously be good for this one and all of the above makes sense to me. I just forgot `cartesian_product` existed when I came to testing different approaches. 

As a user myself, I would look on the `cartesian_product` option as a special case of blocking rather than a separate mode to opt into. Maybe you're trying to emphasise the distinction as a sort of "Are you sure?" to prevent someone accidentally attempting a cartesian join that will blow up?

In my case, I had a working settings dict and then wanted to try the model on a smaller sample of the data without blocking, so the intuitive way seemed to be to remove the blocking rules (i.e. no blocking). By requiring `blocking rules` explicitly in the settings, you avoid that being done accidentally, but can explain in the `description` that an empty array of blocking rules does a cartesian join [insert warning about blowing up].

No problem going with your suggestions above, but it seems a little more complicated than necessary.

**Comment by RobinL** [comment]
OK - that makes sense.  Let's not impose the `numItems >=1` condition then.  

I think we probably do want to raise a warning though, in the case that the user provides an empty list of blocking rules
```
from warnings import warn
warn('message')
```

**Comment by RobinL** [comment]
...I think we've now agreed we can get rid of `cartesian_product` completely, and it will become the default.  if no blocking rules are specified.

**Comment by RobinL** [comment]
In terms of testing, I think  we want some tests within `tests/test_spark.py` of the link_only, dedupe_only, and link_and_dedupe, including the cartesian case using the new rules we’ve just been discussing.

Probably we can use the same data as for the non-spark tests, which is [here](https://github.com/moj-analytical-services/splink/blob/9b7712f40ca8a9b813024c3be605b3e37380f805/tests/test_link_options.py#L29)

If we shift that fixture into `tests/conftest.py` so it is available to many tests, then we can add tests to `test_spark.py` that load the same data in.

Happy to talk through how this all works

**Comment by samnlindsay** [comment]
Have removed references to `cartesian_product` so now `blocking_rules` isn't required in `settings` but will default to an empty list, a cartesian join and a warning about why that might be a bad idea.

Have added `test_no_blocking` to `tests/test_spark.py` having moved the aforementioned fixture to `tests/conftest.py`. By no means a thorough test of the blocking rule behaviour but if  it does the job, I'll tidy it up and add more.

**Pull request merged**
