### PR TITLE
Comparison pseudo symlinks

### PR DESCRIPTION
**Pull request by ThomasHepworth**
### Main Change

This PR adds symlinks to our comparison files, allowing users to import our comparison functions from a simpler path in the future. See issue #1278 for more.

<br>
In code form, this PR replaces the following:<br>

>`import splink.duckdb.duckdb_comparison_level_library as cll`.
with
> `import splink.duckdb.comparison_level_library as cll` 

For future backends, the following [line](https://github.com/moj-analytical-services/splink/blob/comparison_symlinks/scripts/symlink_cls.sh#L3) needs to be updated and the workflow will pick up any additional changes and create the required symlinks.

### Github Action

I've also added a quick github action to automatically produce symlinks for any scripts with the title `{backend}_comparison`. This runs on PR merge.

We may want to disable the action or merge it into [here](https://github.com/moj-analytical-services/splink/blob/master/.github/workflows/pytest_benchmark_commit.yml), so we don't have to perform identical setup twice.

However, for now it's so lightweight that it doesn't hurt to keep it in this form.

### CODE REVIEW

**Comment by RossKen** [comment]
Great job getting this working!

I haven't tested properly yet but one thought - would it make sense to do the symlinks the other way around?
I.e. migrate all the actual code into splink.XXXX.comparison_library etc and symlink to the splink.XXXX.XXXX_comparison_library? 
I guess it doesn't make much of a difference but I think it will make it:
- clearer in the codebase which is our default import method
- easier to get rid of the old splink.XXXX.XXXX_comparison_library directories when we eventually do a v4 release

**Comment by ADBond** [comment]
Looks like a reasonable change - like the new simplified imports. A couple of thoughts that aren't necessary for this PR, but thought would be worth noting here:
* not sure quite what the roadmap is for this, but perhaps at some point leading to v4 we can change these from symlinks to normal modules where we are importing the stuff across so we can add a `DeprecationWarning` in the old places
* there are a few places now where the different backends are used / need to be updated as new ones are added - maybe at some point we an put this into some kind of metadata csv or something so that we only have one point to update

**Comment by ThomasHepworth** [comment]
I'm not sure why the demo notebook is falling over 🤔.

The imports certainly work locally.

**Comment by RossKen** [comment]
Yea I think adding a Deprecation warning would be good here too

**Comment by ADBond** [comment]
> I'm not sure why the demo notebook is falling over 🤔.
> 
> The imports certainly work locally.

No idea why this would be the case (especially when the other tests run fine), but I notice that workflow uses `ubuntu-latest` while the others are pinned to `ubuntu-20.04` (I remember us doing this but forget what was breaking then). Don't see why that should matter but only noticeable difference I could spot so 🤷

**Comment by RossKen** [comment]
I have tested locally and works for me 👍Thanks for switching the symlinks around 🙌

One other annoying thing (sorry). Should we do the same for the linkers too?

I.e. `from splink.XXX.XXX_linker import XXXLinker` -> `from splink.XXX.linker import XXXLinker`

I guess one thing to keep in mind is whether we want to keep the XXXLinker naming that we have or remove the backend specific naming entirely.

I.e. `from splink.XXX.linker import Linker`

Or a less extreme version could be to change our standard syntax to something like

`import splink.XXX.XXXLinker as Linker` 

to reduce the difference between scripts in different backends even more.

**Comment by ThomasHepworth** [comment]
https://github.com/moj-analytical-services/splink/pull/1279#issuecomment-1573749132

I'd be interested to hear your view on this too @ADBond.

I'm fully in favour of adjusting the paths as suggested:
I.e. from splink.XXX.XXX_linker import XXXLinker -> from splink.XXX.linker import XXXLinker

RE: tweaking things such that we can import the linkers like so: `from splink.XXX.linker import Linker`.

Overall, I think the current naming conventions are clearer and I'd prefer to keep them as is. It's easier to determine what linker is in use in any given project and helps us debug should users start asking us questions about "why x and y is breaking".

**Comment by RossKen** [comment]
Yea I agree, I think I got carried away with what we could do rather than should haha

**Comment by RobinL** [comment]
Haven't looked thoroughly, but I wondered about Windows and whether symlinks would work there (or whether it matters for the purpose of this PR, I haven't looked closely enough). But just saw symlinks and thought it was worth mentioning in case

**Comment by ADBond** [comment]
> I'm fully in favour of adjusting the paths as suggested: I.e. from splink.XXX.XXX_linker import XXXLinker -> from splink.XXX.linker import XXXLinker

I agree - think it makes sense given the changes for importing `cl`/`cll`/`ctl`, and feels a bit cleaner.

> RE: tweaking things such that we can import the linkers like so: `from splink.XXX.linker import Linker`.
> 
> Overall, I think the current naming conventions are clearer and I'd prefer to keep them as is. It's easier to determine what linker is in use in any given project and helps us debug should users start asking us questions about "why x and y is breaking".

Also agree. I feel like it would make things harder to reason about, at least for dev work (is this thing the base `Linker` or `SparkLinker` with a pseudonym). I also think there is a distinction here with the libraries: the objects in e.g.`splink.spark.comparison_library` and `splink.athena.comparison_library` (where they exist in common) should behave identically from a user perspective (I think?), so it makes sense for the imports to be fairly interchangeable as any dialect-specifics should be hidden from the user. But this is not quite the case for linkers - things like `AthenaLinker.s3_output` or `DuckDBLinker.export_to_duckdb_file()` are backend-specific, so I think it is useful for users to have a bit of a reminder about which objects are which.

**Comment by RossKen** [comment]
One more fun job on this one - we're going to need to update all the references in the docs to this version 😬 If you can do them in this repo - I will do the equivalent update in splink_demos

**Comment by RossKen** [comment]
@ThomasHepworth all of the imports work great for me and (as far as I can tell) the action looks like it should work fine.

One thing that didn't work as expected was the warnings - loading with the old path doesn't throw anything.

image

**Comment by ThomasHepworth** [comment]
Deprecation warnings aren't thrown by default, which isn't particularly helpful.

Maybe it's best to make a "SplinkDeprecation" warning and just get that to throw warnings.

**Comment by RossKen** [comment]
Ok, should that be a separate PR to this one? To implement a more general "SplinkDeprecation" warning?

**Comment by ThomasHepworth** [comment]
Oops, too late, I already pulled the trigger - https://github.com/moj-analytical-services/splink/pull/1279#issuecomment-1580777238

Can you check if this prints to console for you?

**Comment by RossKen** [comment]
Ah nice - yes that works! Sorry I wasn't sure if that was a bigger piece of work.

**Pull request merged**
