### PR TITLE
ArraySubset defined, first draft

### LINKED ISSUE #2382: [FEAT] A percentage threshold for array intersection
### Is your proposal related to a problem?
We've been working with splink to do a bit of address matching, and have identified cases where:

1. We can't use Levenshtein distance because it wouldn't capture nuance (sometimes if most words match with different ordering, the distance is high when we want a metric that is okay with reordered words).
2. We can't use splink.internals.ArrayIntersectLevel because addresses have different sizes and there's no good min_intersection that we can define.

### Describe the solution you'd like
We've written a patch into our code that's based on splink.internals.ArrayIntersectLevel and defines a new class called ArrayIntersectPercentage that:

1. Takes a percentage_threshold
2. Performs the following pseudocode operation in the sql_base_dialect_sql statement:

$$\frac{size(intersection(left\\_column,right\\_column))}{greatest(size(left\\_column),size(right\\_column)}\leq percentage\\_threshold$$

We would like to make a pull request to this effect, adding this new class to the toolkit that splink officially provides to users as of its current patch.

### Describe alternatives you've considered
As mentioned before, we've considered and attempted to use Levenshtein distance and splink.internals.ArrayIntersectLevel as possible ways of tackling our specific address matching problem, but the patch that we wrote in solved the problem for us, and we think it'll be a nice addition to the entity resolution toolkit.

### Additional context
We're relatively new to open source, and any help in getting this feature on par with the rest of the codebase in terms of standards would be much appreciated!

### PR DESCRIPTION
**Pull request by mihir-packmoose**
### Type of PR

- [ ] BUG
- [x] FEAT
- [ ] MAINT
- [ ] DOC

### Is your Pull Request linked to an existing Issue or Pull Request?

Closes #2382 

### Give a brief description for the solution you have provided
Defines a new class in splink.internals.comparison_level_library called ArrayIntersectPercentage. This class takes two arguments, col_name and percentage_threshold. The functionality here has been tested locally.

No testing yet, will continue adding components as I go along.

### PR Checklist

- [ ] Added documentation for changes
- [ ] Added feature to example notebooks or tutorial (if appropriate)
- [x] Added tests (if appropriate)
- [ ] Updated CHANGELOG.md (if appropriate)
- [x] Made changes based off the latest version of Splink
- [x] Run the [linter](https://moj-analytical-services.github.io/splink/dev_guides/changing_splink/lint_and_format.html)
- [ ] Run the [spellchecker](https://moj-analytical-services.github.io/splink/dev_guides/changing_splink/contributing_to_docs.html?h=spellch#spellchecking-docs) (if appropriate)

### CODE REVIEW

**Comment by mihir-packmoose** [comment]
Hello! I'm trying to figure out a couple of things with this PR:

1. I ran the linter and `poetry run ruff format` changed 27 files, all of which were ipynb files unrelated to my commit. I'm assuming it's fine to not push those changes out and tick off the linter task from the PR checklist?
2. What do my next steps look like? I'm assuming that I need to add tests since this is a code change, but after skimming through the tests, I couldn't figure out exactly where and what form these tests would take.

Thanks and have a great day!

**Comment by RobinL** [comment]
Yeah, happy to accept an `ArraySubsetLevel`, seems like a sensible idea.  I think a slight adjustment to your implementation is needed, something like:

```python
class ArraySubsetLevel(ComparisonLevelCreator):
    def __init__(self, col_name: str | ColumnExpression):
        """Represents a comparison level where the smaller array is an
        exact subset of the larger array.
        """
        self.col_expression = ColumnExpression.instantiate_if_str(col_name)

    @unsupported_splink_dialects(["sqlite"])
    def create_sql(self, sql_dialect: SplinkDialect) -> str:
        sqlglot_dialect_name = sql_dialect.sqlglot_name

        sqlglot_base_dialect_sql = """
            ARRAY_SIZE(
            ARRAY_INTERSECT(___col____l, ___col____r)) /
            LEAST(ARRAY_SIZE(___col____l), ARRAY_SIZE(___col____r))
            == 1
            """
        translated = _translate_sql_string(
            sqlglot_base_dialect_sql, sqlglot_dialect_name
        )

        self.col_expression.sql_dialect = sql_dialect
        col = self.col_expression
        col = self.col_expression
        translated = translated.replace("___col____l", col.name_l)
        translated = translated.replace("___col____r", col.name_r)
        return translated

    def create_label_for_charts(self) -> str:
        return "Array subset"
```

In tersm of testing, you should be able to use an approach like this:
https://github.com/mihir-packmoose/splink/blob/bc18a044cdee713f3278240de6cbd99a27232b6e/tests/test_array_columns.py#L13

i.e. add tests to the `test_array_columns.py` file 

I've checked the above suggestion against duckdb but not spark, so not 100% it'll work there as well

**Comment by mihir-packmoose** [comment]
Hey, Robin! Thanks for your help with where to place the tests and the corrections you mentioned. I've made the necessary amendments, and added some edgecase handling for cases where one array of the two was empty (we had a bit of a division-by-zero problem but it now runs through a preliminary check to make sure that the smaller of the two arrays is not empty). 

A couple of questions here: 
1. Since I'm not too sure about how the @mark_with_dialects_excluding decorator works, I removed the exclusion directive on "spark" since you mentioned that you'd checked the suggestion against duckdb and not spark. I'm presuming that this means my tests also ran for spark, but I'm not sure. What do you think?
2. When we consider mathematical accuracy, $\emptyset \subset \emptyset$. However, me and my team feel that:
-- For this specific application, the mathematical rule need not apply, since we don't expect the function to be required to behave in this manner when invoked; Quite the opposite, we expect that such a comparison should intuitively yield a `False`.
-- In the context that we expect subsets to be used, the expectation should probably be that there are no empty-to-empty matching attempts in the first place.
Even so, we could write a bit of logic into the query that makes it behave mathematically accurately. So we've decided that this should be left to the discretion of the original library authors. Let me know about your thoughts!

**Comment by RobinL** [comment]
@mihir-packmoose sorry for the delay.  Thanks - yes I'm happy with this and agree re: arrays with zero elements.  Are you happy for me to add some commits for tests, and go ahead and merge?

**Comment by mihir-packmoose** [comment]
Sounds good! Thanks again for your help, Robin!

**Comment by mihir-packmoose** [comment]
P.S. I see what you mean by adding commits for tests now, I tried to resolve those conflicts on `test_array_columns.py` and the `literal_utils` file has gone through a complete refactor haha. I'll leave it to you!

**Comment by RobinL** [comment]
I've moved this changeset over to https://github.com/moj-analytical-services/splink/pull/2383 to simplify the merge.  I cherry picked your commits so you'll still appear in the contributors :-)

**Pull request closed without merging**
