### PR TITLE
Custom comparison level and comparison

### PR DESCRIPTION
**Pull request by ADBond**
Defines library `CustomLevel` and `CustomComparison`.

## `CustomLevel`

Provides a wrapper for supplying a `sql_condition`. It additionally allows automatic best-effort translation between dialects (powered by `sqlglot`), so that users don't need to worry so much about writing dialect-dependent SQL.

See test additions for examples of this working in practice.

Edit: altered, see below:
The way it works currently when we create a (dialected) level,:
* `sql_condition` is parsed by `sqlglot`, using an optional dialect the user can specify
*  try to translate to the specified dialect (even if it is the same as the 'initial' form)
* if this fails, just return the original `sql_condition` (which may be wanted if it is e.g. custom stuff, or new features `sqlglot` doesn't know about)

This does mean that SQL expressions can end up more complicated than that specified by user, so may be worth having some kind of flag to turn this transpilation off? That would also catch potential situations where sqlglot ends up spitting out an invalid expression (as was happening with `levenshtein` + `sqlite` initially due to extension-specific stuff, necessitating an alias in our linker) 

Edit: now we only translate if we have a specified dialect and it doesn't match that of the level requested to be made

## `CustomComparison`

A wrapper for supplying a comparison as a list of levels. Any levels which are defined as simple `dict`s will be coerced t `CustomLevel`s, so that:
* we have consistent types, which is useful for things like checking whether levels are null levels (see e.g. #1765)
* we automatically get the translation ☝️ capabilities of `CustomLevel`

That happens with a simple `**kwargs` but should probably be replaced with a proper deserialisation method once we set that up consistently.

Also included:
* blocking rules in new tests to speed them up (most of the time now is making `spark`, where applicable)

Not included:
* automatic coercion to `CustomComparison`, as not clear to me atm when that should happen (but would be useful so that we get the translation even if we define all our comparisons in dict form)

### CODE REVIEW

**Comment by ADBond** [comment]
Went a bit back-and-forth in terms of what the best behaviour should be in terms of the automatic translation stuff in `CustomLevel` - so if anyone has any thoughts / if there are situations I haven't considered please let me know!

**Comment by RobinL** [comment]
Some thoughts on auto-transpilation:

1. Few users switch dialects, so as a feature it's not terribly important
2. Sqlglot 'roundtrips' are imperfect, so I think we should avoid 'self-transpiling' (e.g. `parse_one(sql_str, dialect=x).sql(dialect=x)` does not necessarily output `sql_str`).  It would be surprisingly to the user to see their SQL changed, and could possibly have efficiency implications.
3. I think attempting to auto-transpile to other dialects is a good idea on a best-efforts basis.


One thing that seems fiddly here is users 
    - are likely to provide custom SQL in a specific dialect without setting a base dialect
    - are unlikely to provide 'undialected' custom SQL i.e. in sqlglot's base dialect, because what even is that

On that basis, I think we should assume that the custom SQL corresponds to the dialect in use by the linker, unless otherwise specified.

On this topic, there's another place in the 'un-dialected' API we're thinking about adding support for arbitrary sql:

```python
from splink.comparison_level_library import ExactMatchLevel
ExactMatchLevel("lower(first_name)")
```

When supplying aribtrary expressions in this way, Splink will simply add `_l` and `_r` and leave the rest of the expression unchanged:
`lower(first_name_l) = lower(first_name_r)`

I think we can follow the same pattern here

**Comment by RobinL** [comment]
Consider:

```

from splink.comparison_level_library import CustomLevel
import sqlglot

sql = "datediff('month', l.date, r.date) = 2"

sqlglot.parse_one(sql, dialect='duckdb').sql(dialect='duckdb')
> OUTPUT1: DATE_DIFF('month', l.date, r.date) = 2
sqlglot.parse_one(sql).sql(dialect='duckdb')
> OUTPUT2: DATE_DIFF('date', l.date, 'month') = 2


CustomLevel(sql, 'lab').get_comparison_level('duckdb').as_dict()
> OUTPUT3: {'sql_condition': "DATE_DIFF('date', l.date, 'month') = 2", 'label_for_charts': 'lab'}
CustomLevel(sql, 'lab', 'duckdb').get_comparison_level('duckdb').as_dict()
> OUTPUT4:  {'sql_condition': "DATE_DIFF('month', l.date, r.date) = 2", 'label_for_charts': 'lab'}

```

Appreciate this is subective but I think outputs 2 and 4 are least surprising (obey the principle of least surprise) **to a user who's doing some linking in duckdb**. (i.e. to a user who's just doing some standard, non-cross-backend linking)

**Review by RobinL — CHANGES_REQUESTED** [review]
This looks good - with the exception of the comment about auto-traspilation.  see also my longer comment on the PR itself and the example below it

**Comment by ADBond** [comment]
Yeah, I see what you mean. Definitely don't like the idea of the unexpected self-transpilation - was just trying to get something that worked without users needing to (necessarily) specify dialects.

But I think you're right - best to only do this when is there is a direct clash of dialects (i.e. mismatch between level-specified dialect and that which we use to create) 👍

**Review by RobinL — APPROVED** [review]
LGTM thanks 👍

**Pull request merged**
