### PR TITLE
feat: Support sqlglot >=5.1.0

### LINKED ISSUE #991: bug: sqlglot dep shouldn't be pinned to a specific version
### What happens?

sqlglot is pinned to exactly "5.1.0". I also want to install Ibis, which requires a different version of sqlglot. They conflict and therefore pip won't let me install both libs at the same time.

Usually, as a lib, you want to require as loose of a range on your deps as possible, otherwise this sort of conflict between libs is likely to happen.

Can we simply do `sqlglot>=5.1.0` instead? This might end up being TOO loose, and there might be an issue with sqlglot=6.0.0, but if this happens, it is very easy for me as an application developer to get around this by adding an additional `sqlglot!=6.0.0` dep to my app's deps. It's easy from the app's perspective to make requirements more restrictive, but very hard to make them less restrictive, so generally I think libraries should err on the side of too loose.

I tried this fix on my branch, but `poetry update` had a bunch of errors, so I can leave that to you as an easy fix.

### To Reproduce

`echo $'ibis-framework>=4\nsplink>=3' > requirements.txt && pip install -r requirements.txt`

### OS:

macOS 12.6

### Splink version:

all splink versions >3 suffer from this

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by NickCrews**
Fixes #991 

I had to do some preliminary work before I could start the task at hand, so some commits aren't directly related.

All tests pass on python 3.7+

### CODE REVIEW

**Comment by RobinL** [comment]
Thanks - had a quick look at this Nick.  Would you be able to update to remove python 3.6 support (so this PR is simpler)?

Of if you don't have time,  we can look at raising a separate PR reusing some of this code.

Also would be useful for you to note which parts are the preliminary work, and why they're needed. (possibly two PRs could be easier? up to you). thanks!

**Comment by NickCrews** [comment]
Yeah I'll write a pr dropping 3.6, then can re-do this one. I'll leave this open for now, not sure yet if I'll update it or start fresh.

**Comment by RobinL** [comment]
perfect - thanks so much.  will try to get round to looking at the 3.6 one asap

**Comment by NickCrews** [comment]
Superseded by https://github.com/moj-analytical-services/splink/pull/1018

**Pull request closed without merging**
