### PR TITLE
Sql edit isnull clause

### PR DESCRIPTION
**Pull request by Th368MoJ**
Another one for you.

This changes:
`ifnull((col1=col2), false)` -> `0 = case when (col1=col2) then 1 else 0...`.

Nulls are taken into account when using CASE WHEN (some code is provided in a separate message if you'd like to check).

This one also had some weird benchmarking results (I checked to see if adding in CASE WHEN statements makes a difference to speed).
* `CASE WHEN` example
Screenshot 2022-03-09 at 23 37 05

* Original
Screenshot 2022-03-09 at 23 45 39

On the smaller datasets it's slower when using CASE WHEN, while on the larger df it's actually quicker... Not sure how that one has happened, but fine.

### CODE REVIEW

**Comment by Th368MoJ** [comment]
RE: Nulls proof:

```
import duckdb

con = duckdb.connect()

import numpy as np
import pandas as pd
dict = {
    "col1": ["a", np.nan, "a", np.nan, "a"],
    "col2": ["a", "a", np.nan, np.nan, "b"]
}
test_df = pd.DataFrame(dict)
con.register("testing", test_df)

# con.execute("SELECT * FROM testing").fetch_df()

con.execute("""
SELECT *
FROM testing
WHERE 0 = 
CASE 
    WHEN (col1 = col2) 
    THEN 1
    ELSE 0
END
""").fetch_df()
```

**Comment by Th368MoJ** [comment]
Case when looks to be the way to go on this in terms of speed - https://github.com/moj-analytical-services/splink/pull/337

**Comment by RobinL** [comment]
Also worth noting that `ifnull` does not exist in Athena.

**Comment by RobinL** [comment]
Before we merge, I'm going to test this against the more comprehensive tests at:
`benchmarking/run_synthetic_data_benchmarks_locally.sh`
as I'm interested in Spark performance

**Comment by RobinL** [comment]
Can we use `coalesce(col1=col2,false)` for this?

**Comment by Th368MoJ** [comment]
Closing for now - the issue is that this code seems to cause memory issues when running larger queries.

Current plan is to migrate to using some variation of `coalesce(col1=col2, False)` to generalise the code further and then add a translation step for T-SQL

**Comment by Th368MoJ** [comment]
Closing for now - the issue is that this code seems to cause memory issues when running larger queries.

Current plan is to migrate to using some variation of `coalesce(col1=col2, False)` to generalise the code further and then add a translation step for T-SQL

**Pull request closed without merging**
