### PR TITLE
Basic settings validator

### PR DESCRIPTION
**Pull request by ThomasHepworth**
## Overview
This is a first step towards a more formalised settings validation checker. 

This first iteration checks:
* Builds a framework we can use to add additional checks to the settings object
* Builds in some checks that establish whether the columns entered by a user within `unique_id`, `cols_to_retain`, `blocking_rules` and `comparisons` are valid.
* Migrates `_validate_dialect` to the new settings validation structure.

We may want to extract some of this out further, such that the `SettingsValidator` only contains the final validation steps. But for now, I think this is an appropriate first step.

## How the code works:
There are three classes that I've added that do the legwork:
1. `InvalidCols` - this is a NamedTuple that takes in a list of invalid columns and "why" they're invalid (missing a prefix, suffix or they don't exist in the backing df). This information is then used to produce some output error text through `construct_log_string`.
2. `SettingsValidator` - this is the main workhorse at the moment. This takes in your linker and pulls out the settings information we require to properly assess if anything is invalid. This class can pull columns from SQL and assess if any columns are invalid, or just take single columns and assess if they exist.
3. `InvalidSettingsLogger` - this class simply pulls together our methods within `SettingsValidator` to construct final log strings that are sent to the user's console. These are warnings, rather than errors. Text is only displayed if at least one issue is uncovered by the validator.

This is all then sent to a new method in the linker class - `_validate_settings`, which evaluates whether there is an issue with the settings.

### CODE REVIEW

**Comment by ThomasHepworth** [comment]
## Running example:

For a quick example of the outputs, see:

```py
from copy import deepcopy

import pandas as pd

from splink.duckdb.duckdb_linker import DuckDBLinker
from splink.settings_validator import (
    InvalidCols,
    InvalidSettingsLogger,
)
from tests.basic_settings import get_settings_dict

df = pd.read_csv("./tests/datasets/fake_1000_from_splink_demos.csv")
settings = get_settings_dict()

# Create some wonky comparison levels
email_cc = {
    "output_column_name": "email",
    "comparison_levels": [
        {
            "sql_condition": "email_l IS NULL OR email_r IS NULL",
            "label_for_charts": "Comparison includes null",
            "is_null_level": True,
        },
        {
            "sql_condition": "levenshtein(emails_l, test.email_r) < 3",
            "label_for_charts": "Levenshtein < 3",
        },
        {
            "sql_condition": "date_diff('day', email_date_l, email_r)",
            "label_for_charts": "Random date diff",
        },
        {
            "sql_condition": "ELSE",
            "label_for_charts": "All other comparisons",
        },
    ],
}

city_cc = {
    "output_column_name": "city",
    "comparison_levels": [
        {
            "sql_condition": "city_l IS NULL OR city_r IS NULL",
            "label_for_charts": "Comparison includes null",
            "is_null_level": True,
        },
        {
            "sql_condition": "not_city_l = not_a_city_r",
            "label_for_charts": "Invalid exact SQL",
        },
        {
            "sql_condition": "city_test_l = city_r",
            "label_for_charts": "Exact match",
        },
        # Identical condition - should be ignored by the logger
        {
            "sql_condition": "city_test_l = city_r",
            "label_for_charts": "Exact match",
        },
        {
            # missing _l suffix
            "sql_condition": "sin(radians(\"city\"['lat']))",
            "label_for_charts": "Exact match",
        },
        {
            "sql_condition": "ELSE",
            "label_for_charts": "All other comparisons",
        },
    ],
}

settings["comparisons"][3:] = [email_cc, city_cc]

DuckDBLinker(df, settings, validate_settings=True)
```

**Comment by RossKen** [comment]
@ThomasHepworth I think it would be worth rebasing onto master so you can add validation to the postgres linker

**Review by RossKen — APPROVED** [review]
Hey @ThomasHepworth, this works really well as a framework and gives useful feedback to user which is ace! 🎉

Happy for this to go in as is (once postgres has been added) as a starting point. Is there somewhere that you are planning to add a list of other tests to be implemented over time? May be worth having an issue open on github to collect ideas for cases that should be caught.

**Comment by ThomasHepworth** [comment]
@RossKen I've rebased - can you give this a once-over to check I haven't done anything silly? A second pair of eyes would be good before I destroy anything

**Review by RossKen — APPROVED** [review]
All still looks sensible 👍

**Pull request merged**
