### PR TITLE
Regexp extract - capture group

### LINKED ISSUE #1839: Spark regex extract not working (Splink 4)
Currently using regex extract with Spark causes errors when there is no match - by default it returns the first group, so when there is none, we get an error. We can specify in the argument we want the zeroth group (i.e. full match), but will require dialect-specific functions. Can probably add support for capture group in doing so - see [note in ColumnExpression](https://github.com/moj-analytical-services/splink/blob/20c8fa76ebbd4232c5489ab14fa957ec345d31ed/splink/column_expression.py#L146-L150)

Error: `org.apache.spark.SparkIllegalArgumentException: Regex group count is 0, but the specified group index is 1.`

### PR DESCRIPTION
**Pull request by ADBond**
This implements support for the `capture_group` argument to `ColumnExpression.regex_extract`. As this is not currently recognised by `sqlglot` this is implemented by functions `SplinkDialect.regex_extract`.

I changed the default option to `0` - i.e. full group match.

Implemented for:
* DuckDB
* Spark
* Postgres (partially - probably fixable to extend to capturing higher groups, but didn't feel worth the effort at this point, especially as capturing groups > 1 is niche + avoidable)

Also fixes issue where Spark failed if there was no group defined. 

Closes #1839.

### CODE REVIEW

**Review by RobinL — CHANGES_REQUESTED** [review]
I might be missing something, but I think this needs similar protection to #1834 

import duckdb
duckdb.sql("""           
select regexp_extract('Ebc', '^([ABCDabcd].{1})', 1) 
""").fetchall()

returns 
```
[('',)]
```

Similarly if you forget to include a capture group in your regex you get an empty string:

```

import duckdb
duckdb.sql("""           
select regexp_extract('Ab', '^[ABCDabcd].{1}', 1) 
""").fetchall()
```

<details>
<summary>
script i used to check
</summary>

```python
import logging

import splink.comparison_level_library as cll
import splink.comparison_library as cl
from splink.column_expression import ColumnExpression
from splink.datasets import splink_datasets
from splink.duckdb.linker import DuckDBLinker

ce = ColumnExpression("first_name").regex_extract(r"^[ABCDabcd].{1}", 1)
comparison_first_name = cl.ExactMatch(ce)
comparison_surname = cl.ExactMatch("surname")


cl_settings = {
    "link_type": "dedupe_only",
    "comparisons": [
        comparison_first_name,
        comparison_surname,
    ],
    "retain_matching_columns": True,
    "retain_intermediate_calculation_columns": True,
}


df = splink_datasets.fake_1000
df

linker = DuckDBLinker(df, cl_settings)

logging.getLogger("splink").setLevel(1)

res = linker.predict().as_pandas_dataframe()
res.query("first_name_l == 'Robert' and first_name_r == 'Robert'")

import duckdb
duckdb.sql("""           
select regexp_extract('Ebc', '^([ABCDabcd].{1})', 1) 
""").fetchall()

import duckdb
duckdb.sql("""           
select regexp_extract('Ab', '^[ABCDabcd].{1}', 1) 
""").fetchall()
```

</details>

**Comment by ADBond** [comment]
> I might be missing something, but I think this needs similar protection to #1834

Yeah, I see what you mean. I think this is a little fiddly though - gonna write out my thoughts here for clarity.

The difficulty here is that we need to add this check in arbitrary comparison levels. I.e. if we have some levels
```py
col_expr = ColumnExpression("postcode").regex_extract("^[A-Z]{2}")
comparison_levels = [
    cll.NullLevel("postcode"),
    ...
    cll.LevenshteinLevel(col_expr, 2),  # want this to 'fall through' if this returns the empty string - i.e. those are not captured by this level
    ...
]
```
we would need Levenshtein to output `levenshtein(X_l, X_r) <= 2 AND (X_l <> '' AND X_r <> '')`

This will need to available for all levels _except_ I think `NullLevel`, `ElseLevel` and `CustomLevel`, and only be applied if we have an expression with `.regex_extract` (or more generally any class of expression which could return empty strings - possibly `try_parse_date` in some backends?) Perhaps we can stick another layer in-between the current `create_sql` method and the one that is used by `create_level_dict` to implement this logic?

As this will be a little involved I will open up a separate PR pointing at this branch.

**Comment by RobinL** [comment]
Can we fix it in a general way by simply adding a `.zero_length_string_to_null()` method that can be used on a `ColumnExpression`, then it's up to the user to choose the behaviour they want

**Comment by ADBond** [comment]
Hmmm, I'm a bit in two minds about this. I agree it's not something that would ideally warrant too much extra complexity, but I worry that putting the onus on users makes for nasty errors that can very easily be missed. If a user has something fairly reasonable like:
```py
comparison_levels = [
    cll.NullLevel("email"),
    cll.ExactMatchLevel("email"),
    cll.ExactMatchLevel(ColumnExpression("email").regex_extract("^[^@]+")),
    cll.LevenshteinLevel("email", 2),
    cll.ElseLevel
]
```
they will end up with all invalid emails in the middle level. You might want to not validate emails to catch levenshtein stuff for invalids, and you could easily not notice something going wrong here, especially as the linkage will run just fine.

**Comment by ADBond** [comment]
I'd be maybe more inclined to have `zero_length_string_to_null` as a (by default `True`) option to `regex_extract` (or even have it as always `True` with no opt-out, leaving users to write custom expressions if they really want that behaviour - can't think of a particular use-case off the top of my head)

**Comment by RobinL** [comment]
Yeah - I think i'm on board with just wrapping the whole thing in `CASE WHEN` to ensure it's NULL, with no opt out.

I also can't think of a good use case for zero length strings, except possibly there may be some cases where NULL will break a comparison function like levenshtein.  But in that instance you'd probably want the result to be more like `'abc123xyz'` (that doesn't match to anything) rather than `''` that might fuzzy match to some things.  Feels like to much of an edge case to try and deal with no.

I think I'd err on the side of no opt-out because it's easy to add it in later if somenoe needs it and we have a tangible use case

**Comment by ADBond** [comment]
I've added the guard in for `regex_extract` _and_ `try_parse_date` (i.e. converting to `NULL` if returning empty string) - as such I have also removed the explicit handling in `NullLevel`

**Review by RobinL — APPROVED** [review]

**Pull request merged**
