### PR TITLE
[MAINT] Improve speed of tests 

### PR DESCRIPTION
**Pull request by RobinL**
The main tests (`.github/workflows/pytest_run_tests_with_cache.yml`) are now much faster:
NEW:
image

OLD:
image

See #1707

Various notes below on things I tried

### CODE REVIEW

**Comment by RobinL** [comment]
Possible improvement:
<details><summary>possible improvement</summary>

```python
@mark_with_dialects_excluding()
def test_u_train_link_only_sample(test_helpers, dialect):
    helper = test_helpers[dialect]
    NUM_ROWS = 1000
    df_l = (
        pd.DataFrame(
            np.random.randint(0, NUM_ROWS, size=(NUM_ROWS, 1)), columns=["name"]
        )
        .reset_index()
        .rename(columns={"index": "unique_id"})
    )
    df_r = (
        pd.DataFrame(
            np.random.randint(0, NUM_ROWS, size=(NUM_ROWS, 1)), columns=["name"]
        )
        .reset_index()
        .rename(columns={"index": "unique_id"})
    )
    # levenshtein should be on string types
    df_l["name"] = df_l["name"].astype("str")
    df_r["name"] = df_r["name"].astype("str")

    # max_pairs is a good deal less than total possible pairs
    max_pairs = NUM_ROWS * NUM_ROWS
    target_pairs = max_pairs / 4
    settings = {
        "link_type": "link_only",
        "comparisons": [helper.cl.levenshtein_at_thresholds("name", 2)],
        "blocking_rules_to_generate_predictions": [],
    }

    df_l = helper.convert_frame(df_l)
    df_r = helper.convert_frame(df_r)

    linker = helper.Linker([df_l, df_r], settings, **helper.extra_linker_args())
    # Debug mode is very expensive in Spark - more than just increasing the num rows
    linker.debug_mode = True
    linker.estimate_u_using_random_sampling(max_pairs=target_pairs)

    # count how many pairs we _actually_ generated in random sampling
    check_blocking_sql = """
    SELECT COUNT(*) AS count FROM __splink__df_blocked
    """
    self_table_count = linker._sql_to_splink_dataframe_checking_cache(
        check_blocking_sql, "__splink__df_blocked_same_table_count"
    )

    result = self_table_count.as_record_dict()
    self_table_count.drop_table_from_database_and_remove_from_cache()
    pairs_actually_sampled = result[0]["count"]

    proportion_of_max_pairs_sampled = pairs_actually_sampled / target_pairs
    # proportion_of_max_pairs_sampled should be 1 - i.e. we sample max_pairs rows
    # as we have many more pairs available than max_pairs
    # equality only holds probabilistically for some backends, due to sampling strategy
    # chance of failure is approximately 1e-06 with this choice of relative error
    assert pytest.approx(proportion_of_max_pairs_sampled, rel=0.15) == 1.0
```
</summary>

**Comment by RobinL** [comment]
Prior to checkpoint
image
image

**Comment by RobinL** [comment]
Setting break lineage method to "checkpoint" made things MUCH slower
image

**Comment by RobinL** [comment]
Changing num partitions on repartition didn't seem to help much, but possible slight improvement
image

**Comment by RobinL** [comment]
Those latest settings seem best - both complete in 5 minutes now 

image

**Comment by RobinL** [comment]
I don't really understand why the speed of `test_analyse_blocking_slow_methodology` shows us as so slow in the test log

If you run 10x as many tests, they dont take long (each iteration of the tests takes 0.2 seconds locally)

<details><summary>script</summary>
```python
@mark_with_dialects_excluding()
def test_analyse_blocking_slow_methodology(test_helpers, dialect):
    helper = test_helpers[dialect]
    Linker = helper.Linker
    brl = helper.brl

    for i in range(10):
        start_time = time.time()
        df_1 = pd.DataFrame(
            [
                {"unique_id": 1, "first_name": "John", "surname": "Smith"},
                {"unique_id": 2, "first_name": "Mary", "surname": "Jones"},
                {"unique_id": 3, "first_name": "Jane", "surname": "Taylor"},
                {"unique_id": 4, "first_name": "John", "surname": "Brown"},
            ]
        )

        df_2 = pd.DataFrame(
            [
                {"unique_id": 1, "first_name": "John", "surname": "Smyth"},
                {"unique_id": 2, "first_name": "Mary", "surname": "Jones"},
                {"unique_id": 3, "first_name": "Jayne", "surname": "Tailor"},
            ]
        )
        settings = {"link_type": "dedupe_only"}
        linker = Linker(df_1, settings, **helper.extra_linker_args())

        res = linker.count_num_comparisons_from_blocking_rule(
            "1=1",
        )
        assert res == 4 * 3 / 2

        res = linker.count_num_comparisons_from_blocking_rule(
            "l.first_name = r.first_name",
        )
        assert res == 1

        settings = {"link_type": "link_only"}
        linker = Linker([df_1, df_2], settings, **helper.extra_linker_args())
        res = linker.count_num_comparisons_from_blocking_rule(
            "1=1",
        )
        assert res == 4 * 3

        res = linker.count_num_comparisons_from_blocking_rule(
            "l.surname = r.surname",
        )
        assert res == 1

        res = linker.count_num_comparisons_from_blocking_rule(
            "l.first_name = r.first_name",
        )
        assert res == 3

        settings = {"link_type": "link_and_dedupe"}

        linker = Linker([df_1, df_2], settings, **helper.extra_linker_args())

        res = linker.count_num_comparisons_from_blocking_rule(
            "1=1",
        )
        expected = 4 * 3 + (4 * 3 / 2) + (3 * 2 / 2)
        assert res == expected

        rule = "l.first_name = r.first_name and l.surname = r.surname"

        res = linker.count_num_comparisons_from_blocking_rule(
            rule,
        )

        assert res == 1

        rule = brl.block_on(["first_name", "surname"])
        start_time = time.time()
        res = linker.count_num_comparisons_from_blocking_rule(
            rule,
        )
        end_time = time.time()
        print(f"Iteration {i+1} took {end_time - start_time} seconds")

```
</details>

Is the timing conflating the setup in conftest vs the test itself? 

it shouldn't be (the `call` in the screenshot distinguishes the runtime vs setup), but perhaps there's something in our config that causes them to be conflated.  Perhaps the indirection we introduced to prevent spark always being setup

**Review by ADBond — APPROVED** [review]
Nice speed improvements, looks good to me 👍 
Also a bit clearer what is going on - not so many obscure numbers floating about

**Pull request merged**
