### PR TITLE
Parse tf column with InputColumn

### PR DESCRIPTION
**Pull request by RossKen**
Wrapping `tf_adjustment_column` in `columns_reversed_level` with `InputColumn` function as it is treated as an input column within the function and will, potentially, be different to `col_name_1` and `col_name_2`. Hence, it should be wrapped in `InputColumn` to avoid parsing errors across back ends (e.g. duckdb requiring single quotes instead of double quotes in some instances).

### CODE REVIEW

**Comment by RossKen** [comment]
Thanks for looking at this @ADBond  - I will have a dig into your branch and test.

In term of the error itself - @afua-moj came across it initially so may have the exact error message. But from what I know it was essentially the same as this [StackOverflow issue where duckdb requires single quotes](https://stackoverflow.com/questions/75671499/duckdb-binder-error-referenced-column-not-found-in-from-clause). I'm pretty sure we saw this issue previously wrt one of the the comparison template library functions and solved it with `InputColumn`, but there may be a better way in this instance.

**Comment by RossKen** [comment]
So this shows different behaviour when introduced into the linker in different ways.

1. Works fine when called in `linker = DuckDBLinker(df, settings)`

2. Breaks when called via `load_settings()` e.g.
```
linker = DuckDBLinker(df)
linker.load_settings(settings)
```
Which feels odd, perhaps we need to dig more into `DuckDBLinker` and `load_settings` to make sure they give the same results

**Comment by RossKen** [comment]
Related to #1055

**Comment by ThomasHepworth** [comment]
@RossKen, @ADBond - do we want to close this PR due to the issues outlined above by Andy?

**Comment by RossKen** [comment]
Yea I was just thinking this earlier - closing

**Pull request closed without merging**
