### PR TITLE
Implement Singleton Pattern for Dialects and Refine Dialect Factory Methods

### PR DESCRIPTION
**Pull request by ThomasHepworth**
### Type of PR

- [ ] BUG
- [ ] FEAT
- [x] MAINT
- [ ] DOC

This PR:
1. Implements the singleton pattern for our dialects.
2. Migrates our dialect factories away from using a lookup to using looking up subclass attributes.

<hr> 

New factory pattern - https://github.com/moj-analytical-services/splink/pull/1755#issuecomment-1822392832.

`SplinkDialect` singletons summary:
* There can only be one instance of each dialect in existence within a python instance - i.e we pass the memory address around. As these classes are tiny already, this makes very little difference... but still.
* The `_DialectLookup` class enforces uniqueness - we can only have one mapping to `DuckDBDialect`, for example.

`SplinkDialect` could alternatively be a frozen dataclass here, which would make it immutable (if that is something we desire).

### CODE REVIEW

**Comment by RobinL** [comment]
Looks good to me - let's check @ADBond 's ok with this too before merging

**Comment by ADBond** [comment]
Like the ideas here, and think the singleton pattern for the various `SplinkDialect`s makes sense.

I agree that it would be nice to improve the way we do the string lookup - I actually had a slightly different idea on that, which I bring up as I think there are potentially a couple of advantages. [This is a sketch of it for the db-api](https://github.com/ADBond/alternative-approaches/blob/2298c9cc90ca07a0549e19420ed1971ff97ca1a6/db_api.py#L47-L55) (this version returns the class rather than an instance, but that is not necessary here). This means that we don't need a separate lookup, and the data is stored on each subclass, which I think maybe makes the code a little cleaner. Also in terms of a practical advantage, this allows users to define their own `SplinkDialect` subclass and have the factory method work immediately, without needing to hack our private `_DialectLookup`.

Happy if either of you disagree on this - think the enum solution works fine also

**Comment by RobinL** [comment]
Interesting - i think the two advantages of your approach are pretty compelling

**Comment by ThomasHepworth** [comment]
Love it! Far cleaner and one less lookup for us to avoid updating. More than happy for @ADBond to implement that as our de facto factory method of choice.

Also yes, second what Robin said about not knowing this was possible. More python voodoo to play around with at a later date.

**Comment by ADBond** [comment]
@ThomasHepworth is it okay to push implementation directly to this branch?

**Comment by ThomasHepworth** [comment]
@ADBond - sorry, I was going to say in our slack chat to push your changes directly on here, but a delivery got in my way.

**Comment by ADBond** [comment]
Have added that change now - included some additional tests to check that the behaviour seems sensible, which required a bit of fiddling to ensure that they are sufficiently 'forgetful', which I think now works without being too heavy-handed or needing to hack the implementation directly.

Let me know any thoughts or if anything is unclear!

**Review by RobinL — APPROVED** [review]

**Comment by RobinL** [comment]
Yeah - go ahead - sorry missed this being updated

**Comment by ThomasHepworth** [comment]
@ADBond do you mind resolving the conflict?

**Pull request merged**
