### PR TITLE
(Splink4) ColumnExpression

### PR DESCRIPTION
**Pull request by RobinL**
## Summary

Introduces a new user-facing `ColumnExpression` class which can be used as an input to `ComparisonLevel` or `Comparison`, and (not in this PR) as an input to `block_on()`

Retires the use of `InputColumn` in `ComparisonLevel` or `Comparison`

<details>
<summary>
Try it
</summary>

```python
from IPython.display import display

import splink.comparison_library as cl
from splink.column_expression import ColumnExpression
from splink.dialects import DuckDBDialect
import splink.comparison_level_library as cll

ie = ColumnExpression("dob").try_parse_date(date_format="%m%d").regex_extract("abc")
ie.sql_dialect = DuckDBDialect()
print(ie.name)

display(cl.ExactMatch("lower(dob)").get_comparison("duckdb").as_dict())

ie = ColumnExpression("dob").lower()

display(cl.ExactMatch(ie).get_comparison("duckdb").as_dict())

d = (
    cl.DateDiffAtThresholds(
        "dob",
        date_thresholds=[1, 2, 3],
        date_metrics=["day", "month", "month"],
        cast_strings_to_dates=True,
        date_format="%Y-%m-%d",
    )
    .get_comparison("duckdb")
    .as_dict()
)
display(d)


ie_1 = ColumnExpression("dob").lower()
ie_2 = ColumnExpression("other").substr(1,2)

cll.And(cll.ExactMatchLevel(ie_1), cll.ExactMatchLevel(ie_2)).get_comparison_level("duckdb").as_dict()
```

</details>
<details>
<summary>
try it 2
</summary>

```python
from splink.column_expression import ColumnExpression
from splink.comparison_library import ExactMatch
from splink.datasets import splink_datasets
from splink.duckdb.blocking_rule_library import block_on
from splink.duckdb.linker import DuckDBLinker

df = splink_datasets.fake_1000

settings = {
    "probability_two_random_records_match": 0.01,
    "link_type": "dedupe_only",
    "blocking_rules_to_generate_predictions": [
        block_on(["first_name"]),
    ],
    "comparisons": [
        ExactMatch("lower(surname)"),
        ExactMatch(
            ColumnExpression("first_name").lower(),
        ),
    ],
    "retain_intermediate_calculation_columns": True,
    "additional_columns_to_retain": ["cluster"],
    "max_iterations": 10,
    "em_convergence": 0.01,
}


linker = DuckDBLinker(df, settings)
df_predict = linker.predict()
linker.match_weights_chart()

```

</details>
## Why?

In Splink 3, individual comparisons had complex function signatures, which internally had to repeat lots of logic e.g. in [class ExactMatchLevelBase(ComparisonLevel):](https://github.com/moj-analytical-services/splink/blob/5cae7ad87599e0821c6fa4d6b3de6334f186b0c7/splink/comparison_level_library.py#L124-L125)

```python
exact_match_level("first_name", set_to_lowercase=True,  regex_extract="^[A-Z]{1,4}")
```

implementation:
```python
        if set_to_lowercase:
            col_name_l = f"lower({col_name_l})"
            col_name_r = f"lower({col_name_r})"

        if regex_extract:
            col_name_l = self._regex_extract_function(col_name_l, regex_extract)
            col_name_r = self._regex_extract_function(col_name_r, regex_extract)
```

We now push that logic to InputExpression to make it generic:

```
from splink.input_expression import InputExpression

col = (
    InputExpression("first_name")
    .lower()
    .regex_extract("^[A-Z]{1,4}")
)

ExactMatchLevel(col)
```
and so those if statements now no longer need to live in each `ComparisonLevel`

it also means that internally, for the datediff level, we can write things like:

```python
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        col = self.col_expression
        if self.invalid_dates_as_null:
            null_col = col.try_parse_date(self.date_format)
        else:
            null_col = col

        if self.cast_strings_to_dates:
            date_diff_col = col.try_parse_date(self.date_format)
        else:
            date_diff_col = col

        return [
            cll.NullLevel(null_col),
            cll.ExactMatchLevel(
                self.col_expression,
                term_frequency_adjustments=self.term_frequency_adjustments,
            ),
            *[
                cll.DatediffLevel(
                    date_diff_col,
                    date_threshold=date_threshold,
                    date_metric=date_metric,
                )
                for (date_threshold, date_metric) in zip(
                    self.date_thresholds, self.date_metrics
                )
            ],
            cll.ElseLevel(),
        ]

```

See also [here](https://gist.github.com/RobinL/68c34d970b88bf7f027afebdad610ebf)

## What's the difference between `ColumnExpression` and `InputColumn` ?
*ColumnExpression*
- `ColumnExpression` needs to be instantiated before a dialect is known
-  It needs the ability to apply arbitrary functions such as `lower()`, `substr()` etc. where the SQL will differ between dialects
- In terms of its use in a `ComparisonLevel` or `Comparison`, the only other SQL manipulation it needs is to add `_l` and `_r` to any/all column identifiers.  e.g. `first_name_r` or `coords_r[0]`, which may be nested in `lower()`
- ColumnExpression can accept arbitrary user-provided sql as an input (e.g. `lower(name)`)

*InputColumn*
- Not exposed to the user
- Takes as an input a column name or column reference only (e.g. `name`, `coords[0]`, `coords['lat']`
- Performs a wide variety of transforms (`l.first_name as first_name_l`) that are useful in the backend but are not user-facing

## Further reading

https://github.com/moj-analytical-services/splink/pull/1757
Some notes and examples that were used in the development of this work:
https://gist.github.com/RobinL/12f15f85812594ff62b29e273b8885f7
https://gist.github.com/RobinL/321c51d2dd66ac3694fd0fc0cc8892ff

### CODE REVIEW

**Comment by RobinL** [comment]
- [ ] term frequency adjustments should not be allowed on an `InputExpression` that is not just a 'pure' column name

**Comment by RobinL** [comment]
You should rarely/never pass an `InputExpression` into a `Comparison`because the same cleaning functions are applied to every level.  So in this case you should have done the transform in data cleaning/

In fact, doing so would break any comparisons with a tf adjustment, because it will look for an exact match level, and this will not exist
not exist.

So arguably, we shouldn't allow `InputExpression` into a `Comparison` - it should only allow a column name.

There's a much more obvious use case for  passing an InputExpression into a `ComparisonLevel` such as 

```python comparison_first_name = {
    "output_column_name": "first_name",
    "comparison_levels": [
        cll.NullLevel("first_name"),
        cll.ExactMatchLevel("first_name", term_frequency_adjustments=True),
        cll.ExactMatchLevel("lower(first_name)"),
        cll.ElseLevel(),
    ],
}
```

Note that `ExactMatchLevel` needs to check that its argument is a 'standard' column, otherwise `term_frequency_adjustments=True` should not be permitted since you can't apply tf adjustments to a `lower(first_name)` column

**Review by ADBond — APPROVED** [review]
This seems to work great, and think the overall structure makes sense. There are a few things that might make sense to tweak a bit but that sort of thing can wait to a future PR.
Couple of non-crucial comments

**Review by ThomasHepworth — APPROVED** [review]
The code all looks good.

Is there a reason you opted to omit any tests? I am guessing it's because you want to get the wider tests working first?

**Comment by RobinL** [comment]
Yeah it's a good point.  I don't have the strongest rationale but two reasons would be:
- I want to get the existing test suite passing - that would implicitly cover quite a bit of this functionality
- Once the existing test suite is passing, I want to re-write quite a few of the tests using an approach [like this](https://github.com/moj-analytical-services/splink/pull/1723).  So a lot of the tests will be re-writes of existing tests, as opposed to new additional tests

**Pull request merged**
