### PR TITLE
430 Term frequency adjustment chart

### LINKED ISSUE #430: Add chart to show TF adjustments for specific values
Individual TF adjustments are shown on the waterfall chart but might be useful to have a chart showing the full range of TF adjustments for a column, relative the match weight without adjustment.

For example:
image

### PR DESCRIPTION
**Pull request by samnlindsay**
Closes #430 (once properly tested)

Currently assumes the comparison name is the same as the column name for which TF adjustments are applied - does not work for e.g. `full_name` with an exact match level TF-adjusted on `full_name` but further comparison levels TF-adjusted on `first_name` or `surname`.

```python
chart = linker.tf_adjustment_chart("city")
```

visualization

### CODE REVIEW

**Comment by RossKen** [comment]
@samnlindsay I am getting the following error:
image
I am going to have a dig to see what is going on, but thought I should flage with you incase you recognise it.

Code to recreate:
```
from splink.duckdb.duckdb_linker import DuckDBLinker
import splink.duckdb.duckdb_comparison_library as cl
import splink.duckdb.duckdb_comparison_template_library as ctl

import pandas as pd

df = pd.read_csv("splink/tests/datasets/fake_1000_from_splink_demos.csv")

settings = {
    "link_type": "dedupe_only",
    "blocking_rules_to_generate_predictions": [
        "l.first_name = r.first_name",
        "l.surname = r.surname",
    ],
    "comparisons": [
        ctl.name_comparison("first_name", term_frequency_adjustments_name="first_name"),
        ctl.name_comparison("surname", term_frequency_adjustments_name="surname"),
        ctl.date_comparison("dob", cast_strings_to_date=True, term_frequency_adjustments=True),
        cl.exact_match("city", term_frequency_adjustments=True),
        cl.levenshtein_at_thresholds("email", 2, term_frequency_adjustments=True),
    ],
}

linker = DuckDBLinker(df, settings)
linker.debug_mode=True
linker.estimate_u_using_random_sampling(max_pairs=1e6)

blocking_rule_for_training = "l.first_name = r.first_name and l.surname = r.surname"
linker.estimate_parameters_using_expectation_maximisation(blocking_rule_for_training)

blocking_rule_for_training = "l.dob = r.dob"
linker.estimate_parameters_using_expectation_maximisation(blocking_rule_for_training)

pairwise_predictions = linker.predict()
```

```
chart = linker.tf_adjustment_chart("first_name")
```

**Comment by samnlindsay** [comment]
I expect this is due to the example notebooks I tested this on having `"retain_intermediate_calculation_columns": True,` so we can't take for granted that `__splink__df predict` will contain the TF columns 😢 

The baseline match weight is in the final settings object, so the only need for `df_predict` is to get the TF adjustments for a given value (but surely this is saved elsewhere or can be recalculated directly as it's a simple enough calculation). I couldn't easily find where the `bf_tf_adj_` was calculated internally but I didn't try very hard as using `df_predict` was easy enough. 

It should be a case of changing the first part of the SQL query to create the same table from the TF table rather than `df_predict` but if you don't immediately know how you'd do that, I'll have a go later.

**Comment by RossKen** [comment]
Ah ok, that makes sense. I will spend some time digging around as well and see if I can come up with something

**Comment by samnlindsay** [comment]
Fixed the above issue and at the same time updated so the `column_name` argument refers to the comparison rather than the TF adjustment column. 
```
linker.tf_adjustment_chart("full_name")
``` 
for example may show the chart for multiple comparison levels with different `tf_adjustment_column`s
`full_name`, `surname` etc.)

**Comment by RossKen** [comment]
Great that this is working! I can confirm it now runs without `"retain_intermediate_columns": True`.

Testing it out I have noticed a couple of things:

1. I think `n_most_freq` and `n_least_freq` are the wrong way round
```
chart = linker.tf_adjustment_chart("first_name", 
                                    n_most_freq=20,
                                    n_least_freq=5,
                                    )
chart
```
Gives
image
Which looks to be giving 20 names with the largest match weight boost (i.e. the least frequent).

2. `vals_to_include` should accept a single string for only one name.
Use [`ensure_is_iterable`](https://github.com/moj-analytical-services/splink/blob/6e3a2e177f53a372f29b5fca57cfc3877b2d4c4d/splink/misc.py#L42) function to wrap input strings into a list. Probably within `linker.tf_adjustment_chart`.  Adding a line like
```
vals_to_include = ensure_is_iterable(vals_to_include)
```
should do the trick.

3. There are 2 functions named `tf_adjustment_chart`
One in linker.py which refers to the one in term_frequencies.py. I'm not sure if this is what we do with all other charts, but do you reckon these should have different names to avoid confusion?

4. charts not showing all`vals_to_include`
Taking a sample of the dataset:
```
df.sample(5, random_state=1)
```
Gives the following:
|     |   unique_id | first_name   | surname   | dob        | city            | email                       |   group |
|----:|------------:|:-------------|:----------|:-----------|:----------------|:----------------------------|--------:|
| 507 |         507 | ecalStt      | Parsons   | 1985-11-21 | London          | shirleybaker@smith-hall.biz |      87 |
| 818 |         818 | Geore        | Hli       | 1984-03-15 | Northampton     | nan                         |     143 |
| 452 |         452 | Cunningham   | Ivy       | 1990-11-27 | Norwich         | alyssa01@torres.com         |      77 |
| 368 |         368 | Lewis        | Freddie   | 1971-12-19 | Southend-on-Sea | tyler28@weaver-alvarez.com  |      63 |
| 242 |         242 | Ryan         | Turner    | 1990-03-21 | London          | onorman@walker.info         |      41 |

Choosing 2 of these names in `vals_to_include`
```
chart = linker.tf_adjustment_chart("first_name",
                                   vals_to_include=["Lewis", "Ryan"])
chart
```
only shows "Lewis"
image
and even then does not show a point (but I am guessing that may be because it is such a low value?). 
Could this be to do with "Ryan" not making it past the blocking rules or something? (I haven't checked if that is the case)

In any case, there should probably be some sort of warning message if a user adds a string to `vals_to_include` that doesn't exist.

**Comment by samnlindsay** [comment]
1. I knew that would happen at some point. Most freq -> lowest TF adj -> high rank 🤯 
2. Thanks for the tip!
3. I've followed the same pattern used for other charts where the linker method has the same name as the function it uses. E.g. `linker.waterfall_chart()` references `splink.charts.waterfall_chart()`
4. 🤔 

Re the warning message, I've followed the recommendation and replacing `df[k]=v` with `df.loc[:,k]=v` seems to stop it complaining.

**Comment by samnlindsay** [comment]
Appears to work at my end with a different example... 🤔 

```python
linker.tf_adjustment_chart(
    column_name="birth_place",
    vals_to_include=["hackney", "medway"],
    n_least_freq=10,
    n_most_freq=10
)
```
image

**Comment by samnlindsay** [comment]
One more change to make those middle points more visible than your example above

image

**Comment by RossKen** [comment]
Hey @samnlindsay, I have 

- reworked some of the pandas code to stop the warning above
- added warning when specifying `vals_to_include` that do not exist

On final thing going wrong with the linting is the following error
image

which I haven't figured out how to rewrite so I'm not sure if you have any ideas?

The failing splink demos test relates to different changes so is not relevant here.

**Comment by samnlindsay** [comment]
@RossKen QUICK - merge it before it comes up with another error! 🙃

**Review by RossKen — APPROVED** [review]

**Pull request merged**
