### PR TITLE
Loosen dependency requirements

### PR DESCRIPTION
**Pull request by NickCrews**
Libraries should specify the loosest dependencies possible. They should ONLY exclude versions that they KNOW to be broken. This gives users at the app level the most freedom to choose versions of packages.

For instance, I needed sqlglot>=20 in order to use a new version of ibis, but splink was restricting the version to <19, so pip wasn't able to find a suitable version. But sqlglot >=19 probably works just fine with splink (admittedly, I haven't tested it...)

If a user finds a version that is broken, they will report it, and/or they can restrict the version themselves in their requirements. But it is impossible for users to loosen requirements.

I added comments directly to the pyproject.toml because it isn't obvious this is the right thing to do,
eg haha this already happened once in https://github.com/moj-analytical-services/splink/pull/1080,
but that has rotted since then.
@ADBond @ThomasHepworth for visibility so you understand the reasoning behind that comment.

related: https://github.com/moj-analytical-services/splink/pull/1642

### Type of PR

- [x] BUG
- [ ] FEAT
- [ ] MAINT
- [ ] DOC

### PR Checklist

- [x] Added documentation for changes
- [x] Added feature to example notebooks or tutorial (if appropriate)
- [x] Added tests (if appropriate)
- [x] Updated CHANGELOG.md (if appropriate)
- [x] Made changes based off the latest version of Splink
- [x] Run the [linter](https://moj-analytical-services.github.io/splink/dev_guides/changing_splink/lint.html)

### CODE REVIEW

**Comment by NickCrews** [comment]
hold on, let me actually run tests with the new sqlglot before you merge.

**Comment by NickCrews** [comment]
OK I locked the deps, but I wasn't able to install them, because of the old numpy version wasn't installing (because I have an mac M1 and there wasn't a wheel for that version, so my machine tried to build from source but then that wasn't working for some reason, IDK IDK).

I'm not familiar with poetry, should I be doing `poetry update numpy`? I'm curious why is poetry choosing such an old version to lock to, when I grep through the lockfile I'm not seeing some package that is requiring such an old version of numpy. Any ideas? It would be great if we could lock to a newer version of numpy so that 1. it's faster and more bug free and 2. so I and other m1 devs can install this.

**Comment by RobinL** [comment]
I think there's been an accumulation of problems due to attempting to support old (unsupported!) versions of python which are in use in some government it environments, and wanting to ensure the test runners work, leading to the lock file not being updated for ages. 

I've also run into that numpy problem.  It may be specific to _new_ versions of python, I'm not sure.

I've fixed all these issues on the splink4 branch, but we could probably do with fixing it on the Splink 3 branch too.  I'll put it on my to do list. To check just the sqlglot dependency, probably it's fine to hack it by manually creating a venv, installing Splink using pip and then upgrading sqlglot and running the tests.   Sorry it's such a hassle

**Comment by NickCrews** [comment]
that process sounds good, no worries that's not that hard!

**Comment by NickCrews** [comment]
OK, so looking at the CI failures, both of them are caused by the upgrade of duckdb 0.9.2 to 0.10. Neither is caused by the sqlglot upgrade.

1. [failure 1](https://github.com/moj-analytical-services/splink/actions/runs/7999354532/job/21847024031?pr=1968) found a bug in the test, where we are calling damerau_levenshtein() on a BIGINT. Before, there was an implicit cast to VARCHAR happening, [now they are more strict](https://duckdb.org/2024/02/13/announcing-duckdb-0100.html#breaking-sql-changes). So need to actually make sure our datatype is correct in the test, and it would be great if we could add some safeguards so that if a user has <0.10.0 installed and they do implicit casting, they also get that error. I'm not sure how we could do that on our end? Maybe we just add a warning to the docstring for that function if were feeling lazy? I'm not sure what the exact line of code that is causing that error, could one of you maintainers look into fixing that?
2. [failure 2](https://github.com/moj-analytical-services/splink/actions/runs/7999354530/job/21847023875?pr=1968) is also caused by that same duckdb upgrade. Before, duckdb raised an error, now it doesn't (if I toggle between `python -m pip install "duckdb==0.9.2"` and version 0.10.0 locally, I can get/avoid the error). It's not clear to me what that test is actually supposed to be testing for? Should we just remove the test?

Besides those two tests there aren't any failures in CI, so I think we could merge this.

I tried to test this locally:
```
python -m venv .venv
. ./.venv/bin/activate
python -m pip install -e .
python -m pip install pytest pyarrow networkx rapidfuzz igraph tabulate pyspark "sqlalchemy<2.0.0" psycopg2-binary
python -m pip install "sqlglot==21.2.0"
pytest
```
but the spark tests were failing. Do I need to start some service first? If I run `pytest -m duckdb` then I get the same errors as above.

**Comment by ADBond** [comment]
>   [failure 1](https://github.com/moj-analytical-services/splink/actions/runs/7999354532/job/21847024031?pr=1968) found a bug in the test, where we are calling damerau_levenshtein() on a BIGINT. Before, there was an implicit cast to VARCHAR happening, [now they are more strict](https://duckdb.org/2024/02/13/announcing-duckdb-0100.html#breaking-sql-changes). So need to actually make sure our datatype is correct in the test, and it would be great if we could add some safeguards so that if a user has <0.10.0 installed and they do implicit casting, they also get that error. I'm not sure how we could do that on our end? Maybe we just add a warning to the docstring for that function if were feeling lazy? I'm not sure what the exact line of code that is causing that error, could one of you maintainers look into fixing that?

Yeah we noticed this, and I think we've had report of some other errors coming about to do with indexing. Think fixing up the tests shouldn't be too tricky.
As far as warning goes, if users are writing their own SQL then that's probably on them to figure out - can't see any reasonable way to do that our end. For our built-in components I'd probably like to wrap with casting, but perhaps need to think if that could mask anything weird (and maybe force users to be explicit - we have some semi-related stuff for parsing dates/using regex, particularly with a more flexible syntax in Splink 4)

>  [failure 2](https://github.com/moj-analytical-services/splink/actions/runs/7999354530/job/21847023875?pr=1968) is also caused by that same duckdb upgrade. Before, duckdb raised an error, now it doesn't (if I toggle between `python -m pip install "duckdb==0.9.2"` and version 0.10.0 locally, I can get/avoid the error). It's not clear to me what that test is actually supposed to be testing for? Should we just remove the test?

I'm fairly sure that test is to do with [this issue](https://github.com/moj-analytical-services/splink/issues/1024) about problems inferring datatypes. I wasn't really across that work, but my understanding was that we could handle things for certain cases, but otherwise queries would still break - so we check for this error on input, and fail early if this is going to break (and this is checking that mechanism).
As this is not an issue when using newer pandas (as far as i understand) we can probably ditch this test if that's going to be the version used in CI.

> but the spark tests were failing. Do I need to start some service first? If I run `pytest -m duckdb` then I get the same errors as above.

hmmm, shouldn't need any additional services for the spark tests - they should just run if you have `pyspark` set up. What kind of errors were you getting?

**Comment by RobinL** [comment]
I'm happy with `pyproject.toml` but reluctant to merge this with DuckDB 0.10.0 in the lockfile, due to the typing problems which i want to look at separately.

[Here's](https://github.com/moj-analytical-services/splink/pull/1998) an alternative PR that implements the changes you made to `pyproject.toml` but modifies the lockfile to upgrade only sqlglot (` poetry update sqlglot --lock`).  

@NickCrews would you prefer to modify the lockfile on this PR to align to #1998, or just merge #1998 and close this?

**Comment by NickCrews** [comment]
Thanks @RobinL for finishing this off. Yes that other PR looks great, you should just merge that and close this out!

**Comment by RobinL** [comment]
Closing - we'll merge https://github.com/moj-analytical-services/splink/pull/1998 instead once reviewed

**Pull request closed without merging**
