### PR TITLE
update docstrings for chart saving

### LINKED ISSUE #1441: BUG: docs for saving offline charts are wrong
### What happens?

docs at https://moj-analytical-services.github.io/splink/linkerqa.html#splink.linker.Linker.m_u_parameters_chart

say
```
from splink.charts import save_offline_chart
c = linker.match_weights_chart()
save_offline_chart(c.spec, "test_chart.html")
```

but this gives an error `AttributeError: 'HConcatChart' object has no attribute 'spec'`

However, the following works fine to go directly to Altair.Chart.save()? IDK if this is missing something.

```python
c = linker.match_weights_chart()
c.save("match_weights.html")
```

### To Reproduce

see above

### OS:

NA

### Splink version:

main

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

### PR DESCRIPTION
**Pull request by RossKen**
### Type of PR

- [X] BUG
- [ ] FEAT
- [ ] MAINT
- [ ] DOC

### Is your Pull Request linked to an existing Issue or Pull Request?

Closes #1441

### Give a brief description for the solution you have provided

Update chart saving examples in chart docstrings

### PR Checklist

- [X] Added documentation for changes
- [ ] Added feature to example notebooks at tutorial in [splink_demos](https://github.com/moj-analytical-services/splink_demos) (if appropriate)
- [X] Made changes based off the latest version of Splink
- [X] Run the [linter](https://moj-analytical-services.github.io/splink/dev_guides/changing_splink/lint.html)

### CODE REVIEW

**Comment by NickCrews** [comment]
Looks great to me @RossKen !

**Comment by RobinL** [comment]
Whilst this looks like the best option, unfortunately it's not possible to do it this way.

The reason is that chart.save(.html) produces a chart which works as a standalone web page only if you have an internet connection, whilst this function seeks to allow users in airgapped environments to use the chart.  

So it needs to follow a similar approach as before, but now retrieve the chart spec from the altair chart (sorry can't remember the method for that and am on my phone)

**Comment by NickCrews** [comment]
Ahhh, yes that makes sense. Darn.

It looks like https://github.com/altair-viz/altair_saver solves this with `save(chart, "chart.html", inline=True)    # HTML document with all JS code included inline`?

**Comment by RobinL** [comment]
> Ahhh, yes that makes sense. Darn.
> 
> It looks like https://github.com/altair-viz/altair_saver solves this with `save(chart, "chart.html", inline=True) # HTML document with all JS code included inline`?

Good spot!  So comes down to whether we want the additional dependency.  Since we already have working code, and Splink gets installed on quite a lot of strange infrastructure (often airgapped, with limited access to pypi) I'd probably err on the side of not adding the dependency, but I don't have particularly strong views

**Comment by RossKen** [comment]
Given we probably don't want to add more dependencies, should we close this PR?

**Comment by RobinL** [comment]
There's still a bug, it's just that the charts are now altair.Charts, so to retrieve the chart as a dict you need `chart.as_dict()`  see [here](https://altair-viz.github.io/user_guide/internals.html#altair-chart-to-vega-lite-spec) rather than `chart.spec`

**Review by ThomasHepworth — APPROVED** [review]
LGTM

**Comment by RobinL** [comment]
This is already fixed by https://github.com/moj-analytical-services/splink/pull/1694/files

**Pull request closed without merging**
