### PR TITLE
[FEAT] Splink Labelling tool beta

### PR DESCRIPTION
**Pull request by RobinL**
## Note for reviewers

This PR contain a working **beta** version of the new labelling tool.  A 'beta' banner is displayed within the labelling tool, and a warning is logged when the tool is produced.

The idea is that we merge this 'MVP' version to start to get user feedback, and subsequent smaller PRs can address any problems or add features.

**The javascript, css and html code that represent the labelling dashboard itself are [here](https://observablehq.com/d/0420fc5db15e44ab).  The file slt.js in this PR represents a bundled javascript library that contains my code and all its dependencies, so that it will work fully offline.  I do not recommend attempting to read this code!  Instead my suggestion is that we get this beta code merged and await feedback.**

What follows is more detailed information about the tool and why I've built it 

## Motivation behind tool

We have a range of algorithms in Splink that rely on labelled data.  For instance, labels can be used to estimate parameters, perform accuracy analysis, visualise false positives and negatives, plot ROC curves etc. 

However, until now, the labels themselves have been assumed to exist ‘as if by magic’ - Splink has had no tool to produce them - seemingly a glaring omission. 

One reason for this is that we have an internal labelling tool that works well for our specific MoJ use case, but is not general enough to build into Splink and requires the user to use Python.

## Use cases 

I believe there are two primary uses of a labelling tool:

**Use case 1:** To measure the accuracy of a record linkage model

**Use case 2:** As a tool used by the model builders to iteratively improve a record linkage model.  Manual labelling early in the model building process can help identify additional data cleaning rules and give ideas for how to improve the model specification (e.g. how comparisons are defined).   The labels can also help identify whether changes to the model increase accuracy.

## Objectives

I have various high level objectives for a labelling tool that is built into Splink: \

1. Does as much work as possible for the user to make labelling as quick as possible, such as identifying potential matches and visually displaying differences. 
2. Integrates closely with existing Splink functionality.
3. Makes no assumption about the type of data (e.g. entity) being linked or the user’s IT infrastructure - i.e. is a generic tool that can be used by all Splink users.
4. Should be as easy to access/run as possible; human labellers should not need to have any programming/data science knowledge.
5. Must work in offline environments, similar to the comparison viewer/cluster studio dashboards
6. Allows labelling to be divided up amongst a (potentially large) team of clerical labellers

## Links

[Latest example with all functionality](https://www.robinlinacre.com/splink_example_charts/example_charts/splink3/labelling_tool_dedupe_only.html)

[Latest example to work in sandboxed Jupyter html viewer](https://www.robinlinacre.com/splink_example_charts/example_charts/splink3/labelling_tool_dedupe_only_jupyter_Q52155443-1.html)

[Latest example with 'answers hidden' (splink modelling results hidden)](https://www.robinlinacre.com/splink_example_charts/example_charts/splink3/labelling_tool_dedupe_only_hide_splink_model_info_Q52155443-1.html)

[Jupyter notebook illustrating Splink workflow/integration](https://gist.github.com/RobinL/7512b8b3b31c42b13b5a28aac5a363b4)

## Checks I've done:

[Checking script dedupe](https://gist.githubusercontent.com/RobinL/6562a57e852c7fc5b0fbd9dc2680f628/raw/61927dce4ef2ba08087a310430018947dbabedbb/try_labelling_tool_dedupe_only.py)

- [x] Dedupe only example.  Produce tool, download labels.
- [x] Dedupe only example.  Re-import existing labels and re-download.
- [x] Dedupe only example.  Produce ROC

[Checking script link only](https://gist.githubusercontent.com/RobinL/6562a57e852c7fc5b0fbd9dc2680f628/raw/1b94aba79c842a3d849260d737cb75008a23dbf4/try_labelling_tool_link_only.py)

- [x] Link only example.  Produce tool, download labels.
- [x] Link only example.  Re-import existing labels and re-download.
- [x] Link only example.  Produce ROC

and

- [x] Check that the `view_in_jupyter` and `show_splink_predictions_in_interface` options work as expected

## Potential issues

One thing I thought long and hard about is how to create the list of potential matches. 

Because it feels somehow circular to use Splink/Fellegi Sunter scores to power a clerical labeling tool which itself is meant to check the accuracy of a Splink/Fellegi Sunter model.

For a long time at MoJ we used an alternative scoring approach ([fuzzyfinder](https://github.com/moj-analytical-services/fuzzyfinder)), as a kind of 'independent' assessment.  

However this just amounted to a sort of similar but inferior version of a Fellegi Sunter score (it’s primarily based on term frequencies) so the idea that it was truly independent isn't really true.  

In the end, I’ve decided I’m comfortable with using the Splink scores to find a list of _potential matches._  

So long as you set the threshold match score for inclusion low enough, it is implausible that a true match falls below this threshold.  

More specifically, if such a true match existed:

* I don’t think there’s an alternative methodology that would easily find such a record
* Such a record would be so different from the original record that a clerical labeler would be likely to label it as a non-match.

If we look at a [real-world example](https://www.robinlinacre.com/splink_example_charts/example_charts/splink3/labelling_tool_dedupe_only.html) (i’ve looked at many!), this seems to be validated - the last records on the dashboard have very little similarity to the input record (but nonetheless are the most similar amongst the input dataset).  The reason is that the vast majority of records have no similarity at all!

## Possible to do list for future iterations of the tool, but will not be added for this PR

To Do:
- [ ] Add into instructions a key for FP/TP/FN/TN
- [ ] Refactor drawing code so make column titles more flexible e,g, when adding headers, columns within headers etc.
- [ ] a 'focus record ' control that, when clicked, shows a single record only and a full diff and waterfall chart 
- [ ] should label be categorical? E.g. certain match, likely match, likely non match, certain non match, etc.
- [ ] Update PR to ensure works, and put together quick tutorial notes in gist
- [ ] Option in Splink code to disable splink scores
- [ ] Improve css on controls
- [ ] Deal with the case there are no matches so nothing to output 
- [ ] Include other types of data comparisons e.g. if it's a float do a % difference
- [ ] Add information about comparison level the comparison fell into in the tooltip
- [ ] Add waterfall chart in new cell at bottom on row click
- [ ] Implement a new method `labelling_tool_for_random_sample` which repeatedly calls 'labelling_tool_for_specific_record' for a random sample of records
- [ ] Ability to hide rows that have been assigned labels?
- [ ] Better deal with nulls

Done:
- [x] Add box to template that makes it clear it's a beta/preview
- [x] Highlight Splink match scores/probability using a red to white to green scale
- [x] Exported labels should include source_dataset where needed
- [x] An option on the Python side for 'show information about Splink model'
- [x] Allow import of existing labels for correction
- [x] Clean up code, splitting out different parts of the interface drawing to functions
- [x] In labels csv, there should be indication of which was the sampled record
- [x] Option button to show all cells as a diff view
- [x] dynamically label for false positive and false negative based on label 
- [x] Make sure that the first potential match record is not the original record
- [x] An option for 'view in jupyter' that shows the csv as a text box at the bottom
- [x] Test re-ingesting labels and doing ROCs
- [x] Make sure the source_dataset column is included in the outputs and optionally (true by default) remove self-match
- [x] In the hover, consider putting a proper vs-code style diff.  
- [x] For `link_only`, ensure that only records with `source_dataset` different from the original record are shown
- [x] Add jaro winkler to tooltip
- [x]  Ensuring all elements have appropriate classes to enable better use 
of css styles
- [x] Exported (downloaded) file should take the ID of the original record
- [x] Copy csv to clipboard option, for cases (e.g. jlab) where download is disabled

### CODE REVIEW

**Comment by RobinL** [comment]
- [ ] Make sure the source_dataset column is included in the outputs and optionally (true by default) remove self-match
- [ ] Include other types of data comparisons e.g. if it's a float do a % difference
- [ ] In the hover, consider putting a proper vs-code style diff.  
- [ ] Test re-ingesting labels and doing ROCs

**Comment by RobinL** [comment]
## Todo next:
# Get labelling_tool_for_specific_record working
# Make sure it works for one or multiple input datsaets
# Then make sure we remove the sampled record from the end results

linker.labelling_tool_for_specific_record("1").as_pandas_dataframe()

# Then implement a new method `labelling_tool_for_random_sample`
# which repeatedly calls 'labelling_tool_for_specific_record' for a random
# sample of records

**Comment by RobinL** [comment]
<details><summary>Script for testing the different link types</summary>

```
from splink.duckdb.duckdb_linker import DuckDBLinker
from splink.duckdb.duckdb_comparison_library import (
    exact_match,
    levenshtein_at_thresholds,
)


import pandas as pd
import numpy as np

df = pd.read_csv("./tests/datasets/fake_1000_from_splink_demos.csv")
df["float_num"] = np.random.rand(len(df))

settings = {
    "probability_two_random_records_match": 0.01,
    "link_type": "dedupe_only",
    "blocking_rules_to_generate_predictions": [
        "l.first_name = r.first_name",
        "l.surname = r.surname",
    ],
    "comparisons": [
        exact_match("first_name"),
        exact_match("surname"),
    ],
    "retain_matching_columns": True,
    "retain_intermediate_calculation_columns": True,
    "max_iterations": 10,
    "em_convergence": 0.01,
}


from splink.duckdb.duckdb_linker import DuckDBLinker

linker = DuckDBLinker(df, settings)


linker.estimate_u_using_random_sampling(target_rows=1e6)


linker.labelling_tool_for_specific_record(
    "13", out_path="labelling_tool_dedupe_only.html", overwrite=True, match_weight_threshold=-4
)


##############
# link_only
##############


df_l = pd.read_parquet(
    "https://github.com/moj-analytical-services/splink_demos/raw/master/data/fake_df_l.parquet"
)
df_r = pd.read_parquet(
    "https://github.com/moj-analytical-services/splink_demos/raw/master/data/fake_df_r.parquet"
)



settings = {
    "probability_two_random_records_match": 0.01,
    "link_type": "link_only",
    "blocking_rules_to_generate_predictions": [
        "l.first_name = r.first_name",
        "l.surname = r.surname",
    ],
    "comparisons": [
        exact_match("first_name"),
        exact_match("surname"),
    ],
    "retain_matching_columns": True,
    "retain_intermediate_calculation_columns": True,
    "max_iterations": 10,
    "em_convergence": 0.01,
}


linker = DuckDBLinker([df_l, df_r], settings, input_table_aliases=["_a", "_b"])


linker.estimate_u_using_random_sampling(target_rows=1e6)


linker.labelling_tool_for_specific_record(
    "13", source_dataset="_a", out_path="labelling_tool_link_only.html", overwrite=True,match_weight_threshold=-10
)



##############
# link_and_dedupe
##############


df_l = pd.read_parquet(
    "https://github.com/moj-analytical-services/splink_demos/raw/master/data/fake_df_l.parquet"
)

df_r = pd.read_parquet(
    "https://github.com/moj-analytical-services/splink_demos/raw/master/data/fake_df_r.parquet"
)


settings = {
    "probability_two_random_records_match": 0.01,
    "link_type": "link_and_dedupe",
    "blocking_rules_to_generate_predictions": [
        "l.first_name = r.first_name",
        "l.surname = r.surname",
    ],
    "comparisons": [
        exact_match("first_name"),
        exact_match("surname"),
    ],
    "retain_matching_columns": True,
    "retain_intermediate_calculation_columns": True,
    "max_iterations": 10,
    "em_convergence": 0.01,
}


linker = DuckDBLinker([df_l, df_r], settings, input_table_aliases=["_a", "_b"])


linker.estimate_u_using_random_sampling(target_rows=1e6)


linker.labelling_tool_for_specific_record(
    "13", source_dataset="_a", out_path="labelling_tool_link_and_dedupe.html", overwrite=True
)

```

</details>

**Comment by RobinL** [comment]
Notes about use in jupyter lab/notebook:

- The download button will not work, either when you load an html in jlab, or even if you right click -> open in new browser tab
- This is deliberate - a security feature.  You get 'Dowwnload is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set.'
- You can implement a button that copies the csv as a string to the clipboard like 
```
<details>
<summary> this htlm page >/summary>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Copy to Clipboard Example</title>
  </head>
  <body>
    <h1>Copy to Clipboard Example</h1>
    <label for="text-box">Text to Copy:</label>
    <textarea id="text-box"></textarea>
    <br>
    <button onclick="copyToClipboard()">Copy to Clipboard</button>
    
    <script>
      function copyToClipboard() {
        /* Get the text field */
        const textBox = document.getElementById("text-box");
        
        /* Select the text field */
        textBox.select();
        textBox.setSelectionRange(0, 99999); /* For mobile devices */
        
        /* Copy the text inside the text field to the clipboard */
        document.execCommand("copy");
        
        /* Alert the copied text */
        alert("Copied the text: " + textBox.value);
      }
    </script>
  </body>
</html>

</details>
```

**Comment by RobinL** [comment]
Checks:

- [ ] Dedupe only example.  Produce tool, download labels.
- [ ] Dedupe only example.  Re-import existing labels and re-download.
- [ ] Dedupe only example.  Produce ROC
- [ ] Link only example.  Produce tool, download labels.
- [ ] Link only example.  Re-import existing labels and re-download.
- [ ] Link only example.  Produce ROC

**Review by RossKen — APPROVED** [review]

**Pull request merged**
