### PR TITLE
Backend installs

### PR DESCRIPTION
**Pull request by ThomasHepworth**
### Type of PR

- [ ] BUG
- [x] FEAT
- [ ] MAINT
- [ ] DOC

### Is your Pull Request linked to an existing Issue or Pull Request?
Referenced in https://github.com/moj-analytical-services/splink/issues/1245

### Give a brief description for the solution you have provided
Adds support for optional installs for our various backends.

Moving forward, users will be able to install all backend specific installs by using the syntax:
```sh
pip install 'splink[<backend>]'
```

instead of installing splink and then installing any additional requirements from there.

I've edited the bash script `test_poetry_installs.sh` so you can easily test that this is installing what we're expecting it to.

### PR Checklist

- [x] Added documentation for changes
- [ ] Added feature to example notebooks or tutorial (if appropriate)
- [ ] Added tests (if appropriate)
- [x] Made changes based off the latest version of Splink
- [x] Run the [linter](https://moj-analytical-services.github.io/splink/dev_guides/changing_splink/lint.html)

### CODE REVIEW

**Review by RossKen — APPROVED** [review]
Added some tabs to make the docs render better but otherwise good to go from me

**Review by RossKen — CHANGES_REQUESTED** [review]
Ah sorry, hadn't spotted test failures

**Comment by ThomasHepworth** [comment]
Thanks @RossKen, I'll sort the dependency woes in the morning.

**Comment by ThomasHepworth** [comment]
@RossKen I've updated a few things to allow pandas 2.0 and up to work with Splink.

**Review by RossKen — APPROVED** [review]
Looks great! 👏

**Pull request merged**
